package com.adventofcode;

import org.apache.commons.lang.StringUtils;

import java.util.Arrays;
import java.util.List;

public class d2t1 {

    public static void main(String[] args) {



        String data = "3-5 f: fgfff\n" +
                "6-20 n: qlzsnnnndwnlhwnxhvjn\n" +
                "6-7 j: jjjjjwrj\n" +
                "8-10 g: gggggggggg\n" +
                "5-6 t: ttttttft\n" +
                "6-11 h: khmchszhmzm\n" +
                "4-6 q: qqbjqqqj\n" +
                "6-8 j: gtkwwjjj\n" +
                "13-14 w: lwgwrwczwwhkww\n" +
                "2-4 p: vcnptzdppvpdzp\n" +
                "4-6 n: pmlnzwrnbnxnpmwmhbnz\n" +
                "4-9 w: wwprdwwwx\n" +
                "13-20 b: rbbcbbbbbbbbsbbbbbmj\n" +
                "1-3 r: zwhrnvr\n" +
                "4-6 f: fmfgfcf\n" +
                "13-15 z: zxzzzzzzzzvxkplvzzz\n" +
                "12-18 r: phjqccgmgzmdwxgtrtb\n" +
                "5-19 s: ssssssssssssssssssss\n" +
                "6-7 d: pddqmdd\n" +
                "7-9 p: pwrlpvlhpfpppzp\n" +
                "4-5 m: mpmmmm\n" +
                "9-10 s: ssxsssssrj\n" +
                "6-9 p: lpjrvpppp\n" +
                "6-13 r: rrrzvtrgrhqxqrvrvwzr\n" +
                "1-3 p: dpjp\n" +
                "6-7 w: wkjnmww\n" +
                "1-5 r: cfqhhr\n" +
                "5-9 m: wmmlpgmqmmrm\n" +
                "12-13 x: sxgnwxxkjwrxr\n" +
                "6-8 n: lnnrnnnnn\n" +
                "10-11 q: kqqqzqqfqqqqq\n" +
                "12-17 k: kkkkkkkkkkpkkhgvnjhk\n" +
                "12-13 v: vvvvvvvvvvvvvv\n" +
                "12-15 h: hhhhhhhjkhhhhhth\n" +
                "6-7 l: hmqtlllnllnlmtqnn\n" +
                "6-9 m: mcmmmdnmh\n" +
                "3-5 k: kkhtn\n" +
                "2-4 n: tnfjmnnn\n" +
                "5-6 j: cjwlmn\n" +
                "4-11 b: bcbbkrlgcbbc\n" +
                "5-10 r: rcrcgrrrzwrrxgpzwrcm\n" +
                "3-4 n: znnn\n" +
                "11-14 s: sssjsssssssssss\n" +
                "6-7 d: rwdddddmdddddkdd\n" +
                "1-4 s: gssssskssss\n" +
                "4-5 j: jjjjzj\n" +
                "11-12 j: cjjjgpjxnjjk\n" +
                "3-6 z: zzkdzzz\n" +
                "7-9 d: mkddddqdhddgdd\n" +
                "1-9 d: rxwqcdrswdg\n" +
                "2-4 m: gmmmn\n" +
                "2-4 k: kkkmk\n" +
                "15-16 r: rrrrrrrrlrrrrrrr\n" +
                "1-11 g: grgggcgggcggp\n" +
                "7-8 q: qqqjqqgq\n" +
                "13-14 c: cxccccgccvcpccccc\n" +
                "2-5 j: txvwlls\n" +
                "3-13 w: plwqwhbwdgxcwfmwjl\n" +
                "9-11 g: ggggggggggggggggdgg\n" +
                "3-12 g: ggsggggggpgm\n" +
                "3-11 g: bcgqgxmbjpwm\n" +
                "8-9 z: zxvzrzzzzzdvzzgz\n" +
                "17-18 z: zzzxzzzzzzzzzzzzsw\n" +
                "9-10 t: ftrmtttktttttdtmdk\n" +
                "15-17 r: rjrrprrrrrrrrrrfrrrr\n" +
                "7-8 k: kkkkkkkkk\n" +
                "6-13 n: nnnvnfgntnnnjnnxh\n" +
                "17-19 l: llllflllllllllllqlrl\n" +
                "11-13 d: hdlddddddhxddddkd\n" +
                "13-17 h: hhhhhhhhhhhhnhhhjhhh\n" +
                "1-12 c: ncccczwcnctcwcc\n" +
                "4-5 w: wgwkl\n" +
                "12-13 w: wwwwwwwwwwwwfwww\n" +
                "3-12 s: scssgwshsspsss\n" +
                "15-17 w: wwwwwcwxmhwwwwwwwww\n" +
                "1-3 x: xxxxw\n" +
                "8-9 p: mpppppppzptp\n" +
                "11-12 n: nntnbnnnnnmx\n" +
                "2-10 x: xrspbmkcthqsdxrdxwx\n" +
                "13-14 l: lllllllpllllll\n" +
                "5-10 x: xxxxjxjdrx\n" +
                "7-8 k: kkkkkkjk\n" +
                "9-11 k: vkkkkkkvkkzddbzr\n" +
                "3-8 r: lbrrcwbdf\n" +
                "6-14 l: lgwllrgllllllgllll\n" +
                "6-9 q: nqqkhqqtqgqc\n" +
                "2-4 g: ggxggggggg\n" +
                "12-13 k: kkkkkjkkkkkvf\n" +
                "5-9 b: scvbbpzbbbzbfb\n" +
                "16-17 d: mdddddddddddddcttd\n" +
                "4-10 l: lllflllllllllllllll\n" +
                "3-6 q: qqqqqtqqqq\n" +
                "1-3 n: pblsghl\n" +
                "9-11 v: bvvvmvfvvgtvfpv\n" +
                "4-5 s: ssshq\n" +
                "5-8 g: ggwgnggp\n" +
                "1-4 f: ffmr\n" +
                "4-5 g: ggwzs\n" +
                "4-5 h: fhhqs\n" +
                "10-17 l: clhlllhslxpgljpvlrkl\n" +
                "7-9 m: pnswhtmvmsrmjwrbfz\n" +
                "6-16 v: vvvvqcvvvdzvjvldvv\n" +
                "5-6 c: cntcrl\n" +
                "12-13 n: nnnnnnnnnnnnln\n" +
                "2-4 w: wwww\n" +
                "2-13 w: swrqssmmwrxtw\n" +
                "15-16 z: zzzzzzzzzzzzzzgqzzz\n" +
                "6-8 c: cctvkbdcwcbvhc\n" +
                "1-2 w: wwzdwjtm\n" +
                "1-3 z: mzzh\n" +
                "6-13 t: fttttdwtttttkht\n" +
                "3-9 g: cggfjgqngwmj\n" +
                "1-5 k: pkkkkkkrk\n" +
                "1-5 q: qknqd\n" +
                "7-11 t: tttttckttkb\n" +
                "6-7 q: qqqqqbl\n" +
                "16-17 c: ccccccccccccccctc\n" +
                "2-5 v: vfcnvlvvvxvrnvvvvvv\n" +
                "1-5 w: nwtwnnwwhtwwdwwww\n" +
                "2-10 v: ftvxxbjzlqctp\n" +
                "5-7 d: nddddgddjdbk\n" +
                "8-11 s: wxqjwkcsflssm\n" +
                "17-20 v: vvvvvvvvpvgvvvvvvvvv\n" +
                "6-8 w: wwlwwwqfw\n" +
                "13-14 r: rrrrgrrrrrrrrr\n" +
                "5-6 t: ttttzq\n" +
                "13-14 c: cccccccccccccc\n" +
                "11-12 k: kwzkkkbdkjkk\n" +
                "10-11 t: ttttpttttrwwtttt\n" +
                "3-4 w: ljwwww\n" +
                "7-8 q: ggqzdvqqw\n" +
                "1-3 z: zzsg\n" +
                "1-2 c: crjvdhgwckszmzpcjmr\n" +
                "10-11 n: nngnntnnnqn\n" +
                "7-16 w: bwdgwwwgwwnnqtcwc\n" +
                "4-16 v: vfkvqvvsvnjhfvvv\n" +
                "10-11 p: fgbhpzqvkmn\n" +
                "10-11 w: wswgwqwszwwhwnwww\n" +
                "15-16 t: stwtfxttthptttttt\n" +
                "1-3 v: vlvsdmrv\n" +
                "5-8 z: zzzzfzzz\n" +
                "14-15 t: ttpvtrlqtlcdrlv\n" +
                "2-6 b: qwfnbkc\n" +
                "6-9 p: jppjpspplm\n" +
                "3-4 s: brgqssz\n" +
                "2-6 q: cqwqlq\n" +
                "13-14 d: rrdljqdddddcxzdc\n" +
                "8-13 s: tsnssssssssrcssrssq\n" +
                "7-8 d: dwddddgl\n" +
                "9-15 b: gspmhlgbbzbbbrbt\n" +
                "3-4 h: khhh\n" +
                "3-4 c: nkccpmcct\n" +
                "6-7 g: ggggggg\n" +
                "17-18 p: ppppppppppppppppjnp\n" +
                "2-6 f: rfjxtff\n" +
                "3-4 g: ggvg\n" +
                "7-9 k: kkkkkkkkkkk\n" +
                "11-16 f: fjdffrtfffjfdffcln\n" +
                "4-8 w: lhpdwbnfssswwfswwwrw\n" +
                "5-9 l: lvlllflll\n" +
                "5-6 t: wtrtlr\n" +
                "4-8 m: mnmmjgqtgs\n" +
                "5-11 n: nnrngbnntnk\n" +
                "5-8 s: ssssfssss\n" +
                "7-14 m: hrnbhsfcvdmxbmvzfvnq\n" +
                "1-5 x: xxxxxxxxwxxdg\n" +
                "1-10 v: vcjvvjvvvv\n" +
                "5-10 l: vvdmhskmprszklvvl\n" +
                "3-17 d: dsddkddddddqddddfjdd\n" +
                "9-13 p: pppppppptpppqp\n" +
                "12-13 h: hhhhhhhhhhjhh\n" +
                "1-4 z: mrvlzlzhzlp\n" +
                "3-4 h: hhmc\n" +
                "7-17 w: wwwwwwwwwwwwwwwwww\n" +
                "6-8 z: cgzxzznzzdhcvwh\n" +
                "4-5 g: mgggg\n" +
                "7-8 t: ttrthtdkjtgtts\n" +
                "8-9 w: wwwwwwwpw\n" +
                "9-15 k: kkkkkkkkkkkkkkk\n" +
                "8-14 q: qqqqqqqqnqqqqq\n" +
                "14-19 w: jkwbwwlwdcmwmmwwrwr\n" +
                "4-5 m: hsxgkdmz\n" +
                "2-4 v: vsvqvcv\n" +
                "4-9 h: grhnhhmhhxhlh\n" +
                "6-14 t: tmttrjbtjtfttc\n" +
                "1-4 d: pjdbrb\n" +
                "15-16 r: rrrrrblrrrrrrrxwr\n" +
                "16-18 p: pppjpppppptpplpppppp\n" +
                "4-7 x: mxtngxnpsx\n" +
                "9-10 b: bbbdbqvmrgbzbbbb\n" +
                "4-5 w: wwwwj\n" +
                "1-2 d: dgws\n" +
                "3-10 l: lglsphlbgfmgdtw\n" +
                "10-11 h: hhhhhfhhhpdhh\n" +
                "5-9 x: xxxxqgxxjf\n" +
                "11-19 m: bfmxmmfgzzhqwsmgwmlr\n" +
                "10-14 x: xxxrxkxxqrlxmpxbdx\n" +
                "3-8 l: lxlxvwlllznlptfv\n" +
                "5-9 h: hhthhhhshdq\n" +
                "1-5 q: sqqqqqqq\n" +
                "9-14 j: jxfcjpjfjjgjjjjjjjhj\n" +
                "1-7 g: gvdgjgsvvgnd\n" +
                "2-5 t: tmttpttttt\n" +
                "17-19 c: ccccclcccccccccccccc\n" +
                "10-13 d: mdvddtsddrxtx\n" +
                "11-12 g: gggggggwggzgp\n" +
                "3-5 k: hzxnpkq\n" +
                "9-11 q: qqqqqsqqqqq\n" +
                "8-9 x: btrkbxngx\n" +
                "3-5 g: jpkchcxcxhzfhsggqkg\n" +
                "7-13 s: ssssssssscssssn\n" +
                "13-15 p: pppppppnppppppp\n" +
                "5-15 f: ffffjfffffffffgf\n" +
                "2-4 p: zqphp\n" +
                "1-4 r: wrrr\n" +
                "3-9 b: jsjcbrkkczkzmjbg\n" +
                "1-2 k: kkkkl\n" +
                "2-3 n: dlnxjwzstsdxns\n" +
                "7-14 v: fvvvvzhhvpsvvckdvv\n" +
                "2-8 r: rrrrwrhrrrr\n" +
                "5-8 n: nnxdnnnnnn\n" +
                "5-12 c: scmcdscccccmcc\n" +
                "9-10 v: vvvvvvvvjm\n" +
                "14-15 w: lwppdwwwwdmrrww\n" +
                "6-7 c: qcgcvxdrcccpxchrnlq\n" +
                "8-10 x: hbrqsksxwxxttz\n" +
                "18-19 w: jnftgwpwmwfdgrcpkww\n" +
                "3-4 k: ffkj\n" +
                "5-9 f: flffsvffsff\n" +
                "3-4 k: kkkkk\n" +
                "1-3 l: dlglkll\n" +
                "10-16 f: bfffjzfffnfffffxhfff\n" +
                "11-20 d: ddbdqsddddddddddfddd\n" +
                "6-20 l: vmjltmkclbmqrflzgdzl\n" +
                "5-19 f: ffffffffffffffffffff\n" +
                "5-10 n: nnnnmnnfnz\n" +
                "4-13 f: kmrfrfkvjxdbftvhnsdm\n" +
                "10-11 k: kkkkkkkkskk\n" +
                "12-13 k: kkkkkkkkkkkhj\n" +
                "7-8 p: ppppppnhw\n" +
                "5-8 l: gtpllwklh\n" +
                "13-14 h: hhhhhhhhzhhwsrh\n" +
                "7-15 h: hhhhhhthhhhhthqgfh\n" +
                "1-3 f: mfdmhv\n" +
                "15-16 f: fffffflfffffffbqf\n" +
                "12-13 c: cccmcccccccxn\n" +
                "2-12 q: nqltxqfdcrxqvt\n" +
                "8-10 d: dddddddddvdddd\n" +
                "2-9 g: mdrwnvtsd\n" +
                "12-13 l: lllllllllllll\n" +
                "2-3 m: mnrgmdm\n" +
                "6-9 v: hvvvvvvvv\n" +
                "4-7 q: bqqqrqcqqqq\n" +
                "8-11 v: vvvvdvvvvvr\n" +
                "3-4 n: cnnw\n" +
                "2-12 r: rrrklfrrrksrr\n" +
                "2-12 p: pxppklhsppwdxwcpzvm\n" +
                "10-11 n: nnnnnnnnnnn\n" +
                "5-6 w: wfwwww\n" +
                "3-5 p: pppppp\n" +
                "3-8 g: ggggggggggggggg\n" +
                "1-4 x: xxxxx\n" +
                "11-16 d: ngcdkglddtppbddgdrd\n" +
                "11-12 k: kkkkkkkkkkhr\n" +
                "12-13 c: hgxxchcvxpdlsrt\n" +
                "1-3 m: vmmm\n" +
                "4-6 z: kvzgzzzp\n" +
                "11-12 d: dzddzlcbvdxk\n" +
                "10-11 g: ggsgggggggggdz\n" +
                "6-8 q: xfhgpqltbfbdzqg\n" +
                "4-7 v: vvvlvcxmvvxq\n" +
                "5-7 v: vkkgvgvnpvvlpgkv\n" +
                "6-7 b: bbkvnwbqblbvbb\n" +
                "2-4 l: wmll\n" +
                "6-9 j: djqjcxxljm\n" +
                "3-4 j: nmzcsnlnjjjdms\n" +
                "3-8 w: wnwwsvww\n" +
                "9-20 m: wbntxzztwmblxmsmltmg\n" +
                "7-8 r: rprrrtrf\n" +
                "1-3 r: lnrfxfswmhgvf\n" +
                "5-12 k: zlkdlktsrqjt\n" +
                "13-14 v: vvvvvvvvvvvvvbv\n" +
                "11-12 d: ddddddddddgc\n" +
                "9-11 c: mdwpjjcdcrc\n" +
                "5-6 m: mmmmnl\n" +
                "5-6 l: lblldn\n" +
                "13-14 c: sccfcxsnsclccc\n" +
                "4-5 q: qqkkq\n" +
                "5-8 m: mmmmmmmm\n" +
                "5-8 z: tzhzzttzvwfcv\n" +
                "12-15 b: bbbbbbbbbbbtdfb\n" +
                "7-10 b: bbnplbbxxbh\n" +
                "1-7 x: zxxxxxvx\n" +
                "6-17 b: kbnbbbbbptbbrbbbb\n" +
                "1-3 l: llllll\n" +
                "13-15 c: ccccccccccccqcz\n" +
                "1-8 s: sssssssb\n" +
                "12-19 x: xxxxxxxxpxxcxxxxxxq\n" +
                "12-13 x: xxxxxxxxxxxxxx\n" +
                "14-18 w: wwwwwwwwwwwwwlwmbk\n" +
                "7-8 q: mzwqblqqz\n" +
                "1-7 p: hrppppgdzp\n" +
                "2-7 n: qmvpmsjncgkgpbb\n" +
                "8-10 x: xxxxxxxwxx\n" +
                "2-4 v: rfcpmpvsswsrjkxpdrxh\n" +
                "14-16 k: kkkkkkkkkkkhkkskkt\n" +
                "14-15 d: ddddddkdddddrqdd\n" +
                "4-16 m: njmqmmmjfmmxhmwgdbc\n" +
                "12-13 h: hdmdfhhhzhkdhr\n" +
                "3-14 n: nbntrsmnmrcwbf\n" +
                "6-8 h: hhwhhlhnhh\n" +
                "18-19 v: vvvvvvvvvvvvjvvvvvp\n" +
                "11-20 l: ldllllbvllmqllmlllfl\n" +
                "2-3 d: dcddd\n" +
                "4-6 n: bsnncn\n" +
                "3-6 f: dwlfqfzgs\n" +
                "8-12 d: xdddddfhnddfddd\n" +
                "5-13 l: llllqlllllmllll\n" +
                "10-14 m: mnmzrmmmmwmmqm\n" +
                "3-12 c: qjchcclnbccccpc\n" +
                "7-16 j: jjjjjjwjjjjjjrjnjj\n" +
                "1-10 v: svvdvvgmgpkfkvhvv\n" +
                "2-4 b: gbpbczblbbv\n" +
                "7-9 w: drwwbwtgwswwww\n" +
                "2-8 h: fhkprhplz\n" +
                "1-6 m: mmmmwm\n" +
                "3-4 g: gggp\n" +
                "1-3 q: qqqqj\n" +
                "10-11 h: htfrdwrnkzntnfpdmkhq\n" +
                "5-6 x: nxxxxxxxj\n" +
                "7-8 w: wwwcwwww\n" +
                "1-5 h: lhhhhh\n" +
                "7-8 f: ffjfftff\n" +
                "3-5 g: kdgfgjgbghggp\n" +
                "2-11 p: flgpvfbhpzxmmntw\n" +
                "12-13 z: zzzzzzhzzzzgzzqz\n" +
                "12-13 j: ttmhmdfjpdpnj\n" +
                "5-7 h: hhhhvhh\n" +
                "9-13 x: xhxbxxsxxqwxxvxxxx\n" +
                "1-3 c: ccchcc\n" +
                "2-5 h: hhrsh\n" +
                "1-3 q: rqqq\n" +
                "2-8 x: sxrxbcxx\n" +
                "12-15 b: bbbbnbbrbcbtbbb\n" +
                "14-18 m: hmmmmmmmkmmmmmmmmrmm\n" +
                "1-4 v: vvvv\n" +
                "5-11 h: brnzvqhrrwh\n" +
                "4-10 f: dbtfdvlfnffqmwp\n" +
                "3-16 r: krrrvmrwrrrtrrrrkrwr\n" +
                "11-15 c: gxbccccccccccbh\n" +
                "13-18 z: zzrzzzzzzzzzzzzzzzz\n" +
                "1-3 l: lkvxtrthfvmdzn\n" +
                "7-9 p: vpppmpppppp\n" +
                "3-4 w: wwwwwwww\n" +
                "8-11 z: vlzzzlzvzzmzzz\n" +
                "2-4 v: vqfv\n" +
                "10-11 s: sssssslssgss\n" +
                "4-5 z: zzzww\n" +
                "11-19 p: zpbpdjfjpdfgnpphhpg\n" +
                "1-8 f: fftlxmfl\n" +
                "9-10 p: phlpqzppxpxp\n" +
                "5-7 q: kbqjqqq\n" +
                "3-6 m: jcblmv\n" +
                "9-10 l: llllllllll\n" +
                "13-14 w: wbwhwwwwhwqwmswwmjwf\n" +
                "6-11 j: jjjjvtjwjbdjj\n" +
                "4-8 j: jljjjvgj\n" +
                "3-4 r: lrhvrzrr\n" +
                "2-4 p: plpfkphpq\n" +
                "2-6 b: bbbbrbvwbbgh\n" +
                "2-11 t: mmjmcwcdcbtztxfbtst\n" +
                "7-15 r: grsrrjrrtrgvrtrrr\n" +
                "6-17 d: dddddgddpddzddddddd\n" +
                "3-10 t: qpnbrnmmjtjxtdg\n" +
                "6-7 v: vvvvvhb\n" +
                "5-20 j: vxmkjnssjdtldsdwltlg\n" +
                "7-10 r: rrrrrrrrrrr\n" +
                "2-4 r: rrpl\n" +
                "3-4 m: mmzg\n" +
                "1-8 h: fshhjrhm\n" +
                "5-8 m: mmmvmmvmmnmdxnjcjpn\n" +
                "8-10 m: mmmmmmmlmzmm\n" +
                "14-15 q: qqqqqqqqqqqqqqb\n" +
                "6-16 q: qhkdtqnzqqqjgjrqrkbq\n" +
                "3-9 b: gtbbfgfhbs\n" +
                "14-16 h: hhhhdhhhmhhhhmhhh\n" +
                "9-10 n: nnnndnnnvjnl\n" +
                "11-12 p: pqpppppppppppp\n" +
                "7-9 d: ddpwfdtdd\n" +
                "6-10 z: qzzzzjzzmz\n" +
                "9-14 q: qqdjqdqqrqqwqnqqp\n" +
                "6-7 k: kkkkkbkk\n" +
                "7-14 j: hjvjmzkhgltffljjvjj\n" +
                "4-5 z: znhzz\n" +
                "11-16 r: rrrrbxdrrqrrsrrb\n" +
                "5-8 v: vvhvvvvvwvlvhlqg\n" +
                "4-10 n: wvnnjnndcnk\n" +
                "5-6 g: ggkggk\n" +
                "8-9 w: wwwwwwwww\n" +
                "5-9 r: mrwrrrrrx\n" +
                "4-6 r: jcfrjrrrg\n" +
                "6-9 w: wkwwsxwgfcwqb\n" +
                "5-6 x: grxjxnrb\n" +
                "2-7 s: nsmldnsszdk\n" +
                "5-9 j: gjjzkjvjwjcjbj\n" +
                "6-11 r: jtrgcvwccrrrfmj\n" +
                "7-12 j: jfjjmjjjjxjqzdjjxq\n" +
                "1-2 n: nnwqcnr\n" +
                "5-16 l: lllpclllllllblllll\n" +
                "5-6 j: wjgdjcdpjxfjxnjj\n" +
                "3-16 s: klstwqksfclmcbbcn\n" +
                "17-18 t: ttttdtttttthtttttttt\n" +
                "9-13 p: ppppppvpvhhqp\n" +
                "1-2 n: tsnnn\n" +
                "3-4 p: jpqpjmpplpw\n" +
                "4-6 t: dtfthsxtfpd\n" +
                "2-6 m: zhszctkm\n" +
                "1-13 p: dppmkpbprgppxcpvhrpz\n" +
                "2-7 m: gvmmflp\n" +
                "9-16 c: rcdsppjbcwdxnfbc\n" +
                "5-15 p: pppxpppqnhpptpppz\n" +
                "10-13 q: xfhqhkqkjqjwqqcfrgl\n" +
                "14-15 t: tttttttttttttdvtttt\n" +
                "5-8 q: qqqbqvqzqqn\n" +
                "1-7 v: cvgvvbcgjv\n" +
                "6-9 r: rrrrrrrdr\n" +
                "2-11 j: wjjgxngswkj\n" +
                "11-13 d: dddddddddddddm\n" +
                "5-8 p: pzppppppkjp\n" +
                "15-16 c: cccccccccccccctc\n" +
                "1-7 c: vsvkccbc\n" +
                "2-5 h: hhhhchhhhhhhhhh\n" +
                "9-11 n: nnnnnnnnnnnnn\n" +
                "11-12 q: mdmfmkxcxzjq\n" +
                "6-11 m: mmkgnjdhfbc\n" +
                "1-4 d: dgrdwbdfdkdrmthsj\n" +
                "12-14 k: kkkkkkkkkrjkkkkk\n" +
                "2-4 d: hdrvdzd\n" +
                "2-3 s: sxmsssssssssssssssss\n" +
                "13-15 z: zzzzzzlzzlzztzzz\n" +
                "3-8 r: lxrrrnvrtrgnmkrr\n" +
                "6-7 w: wwlbrwwww\n" +
                "4-7 r: zlnmmkpnrkkcrrxrmfq\n" +
                "2-6 v: zgvvjjvvjhjv\n" +
                "8-11 l: llllllllllcl\n" +
                "8-14 m: mlmldmmgnqzmmmm\n" +
                "7-10 z: wzzzzhtzdqzznzz\n" +
                "4-7 k: mvgwkkk\n" +
                "5-9 p: pdpltvdpptpppg\n" +
                "4-15 q: qqqfqbzqlqqqqqpqfqs\n" +
                "5-7 q: qqqcxqqm\n" +
                "14-17 x: rltjxxbxxxllsxwcx\n" +
                "1-13 w: gwggwwwwwwbsbwkwwd\n" +
                "8-14 k: kkbkkkkhkkkxjzblgk\n" +
                "5-8 p: cppnpprp\n" +
                "6-7 k: jrnvhkkgkkb\n" +
                "12-14 h: hhhhhhhhhhhhhn\n" +
                "10-20 j: gjwjjjpjjljjjjjsjjjj\n" +
                "16-17 n: nnnnnnnnnnnnknnnnn\n" +
                "5-6 f: cdpppf\n" +
                "12-13 z: bvpzqzzlwzccfszt\n" +
                "1-9 k: wdkkvtrprltkkltz\n" +
                "9-16 x: xxxjxdxhtzjxgxsbx\n" +
                "17-18 j: jjjjjjjjjjjjjjjjlrxj\n" +
                "2-5 x: xkknmxxxn\n" +
                "3-9 f: tfffhfffffff\n" +
                "11-16 r: rrlgrrqmrrprcrrrvjr\n" +
                "9-12 m: nrlmgmxvgkmpmqvntx\n" +
                "4-7 r: hrrrzrrnm\n" +
                "3-15 g: stgjgbgggvdljcgdgfg\n" +
                "6-9 j: jjjzbpjjjjjj\n" +
                "2-3 p: ppjp\n" +
                "9-10 t: tttttttttt\n" +
                "10-12 w: wwwfwvwvnkwdwww\n" +
                "11-14 d: nvljddddftrndzx\n" +
                "6-7 r: rlrrrbqcrqr\n" +
                "2-4 c: xbdl\n" +
                "11-18 c: ccccccccccvcccccccc\n" +
                "5-6 j: gjjjjjj\n" +
                "3-7 w: xwhnqlhnpfrvlkqqrp\n" +
                "6-19 q: qqqfxdglhqqkqqqjnhdq\n" +
                "8-9 d: ddsdddqsv\n" +
                "14-16 g: gggggggggggggggt\n" +
                "3-5 b: bbbnh\n" +
                "11-14 t: mtttwttfttttltq\n" +
                "8-10 x: xxxcxxxfxq\n" +
                "8-11 l: lfgvnlzrfcllnxss\n" +
                "1-3 t: gtttttttwgtptt\n" +
                "1-20 j: jjgjlqjjcjcjjjsjgjlj\n" +
                "8-14 v: dqgmngvvqnswvvrrvc\n" +
                "2-8 m: gmpkmmsmmmmm\n" +
                "5-6 m: mmmmtm\n" +
                "6-7 z: zfzrxzxz\n" +
                "4-15 k: wmwkhhskgwzqpnk\n" +
                "2-6 d: hddddfzdsdtvg\n" +
                "9-10 g: gggsggggggrgggqg\n" +
                "11-12 m: mmmmmmmmmmmm\n" +
                "5-7 w: wwhqqhwwwwd\n" +
                "4-9 k: gtkrkkkdfk\n" +
                "1-4 g: kgtvg\n" +
                "7-11 r: rhdbzjrwrcr\n" +
                "9-18 f: fjffffffdffkfffffvf\n" +
                "3-5 t: ttttt\n" +
                "13-14 q: qqqqqqqqqqqqcqqq\n" +
                "1-8 n: vnnnnwnqlbln\n" +
                "3-5 s: ssmss\n" +
                "2-4 q: qqqbkvqxh\n" +
                "3-4 n: nshscq\n" +
                "10-18 s: sssssssssnsssssssgs\n" +
                "9-10 v: vvvvvglvzddvvjv\n" +
                "5-16 s: sspssssrssssslss\n" +
                "4-7 t: ttptxtt\n" +
                "2-4 r: rrrrrxdrr\n" +
                "8-9 b: xqvbbbbbh\n" +
                "3-4 b: bbbbc\n" +
                "1-13 v: qhvvvvlvvvvvdv\n" +
                "4-8 l: lhkllblwllll\n" +
                "3-4 q: qhjgq\n" +
                "8-9 p: rpbpppshdpp\n" +
                "13-18 k: kkkkkkkkkkkkkkkkkx\n" +
                "8-9 r: rrrrrrrrr\n" +
                "5-10 f: bjfwwqvjwffpnl\n" +
                "1-3 l: pbhl\n" +
                "4-6 g: mggfgv\n" +
                "1-4 t: tttttt\n" +
                "5-10 t: llqrtccxtttntxjcdczk\n" +
                "13-14 q: qqqqmqqqdqqfqgqqqq\n" +
                "6-10 w: wpwmwwrgwwk\n" +
                "13-16 q: qqshgkqkqvscqtqq\n" +
                "4-5 t: qttdt\n" +
                "2-12 h: fpbbxgpskzjpkvtr\n" +
                "10-12 z: zrszvzzzzrzkznpzw\n" +
                "1-4 z: tgzz\n" +
                "3-6 c: cdwccvgm\n" +
                "1-15 q: jqqxkqrqmtfqpvbpq\n" +
                "4-6 v: vjvlvvv\n" +
                "1-7 l: hjlllwj\n" +
                "6-13 s: lrspslfwsgjks\n" +
                "3-4 p: dpvk\n" +
                "4-8 h: hsjjhhff\n" +
                "1-18 k: pkkkkkkkkkkkkkkkkkk\n" +
                "6-8 n: nvcnxqnnrnnn\n" +
                "7-8 p: ppppppvzp\n" +
                "12-17 h: hhhhhzhhhhhkhhhhph\n" +
                "13-17 p: ppmpppnppppplpbvcppp\n" +
                "8-14 m: tmmcjvmmjgcfmmnj\n" +
                "1-3 t: tttth\n" +
                "3-4 x: zxxx\n" +
                "1-3 d: kpwhxpctcgdbdkb\n" +
                "5-6 z: knnlzzzzxjrghzb\n" +
                "9-10 w: wwmwwwwxgww\n" +
                "9-11 b: bqbbfbbwbbqbb\n" +
                "2-3 d: ddxp\n" +
                "10-12 g: gggvgsgtgggggbg\n" +
                "3-4 b: gbbb\n" +
                "8-20 c: jccqcxjcqfncfcbccgcc\n" +
                "4-9 z: zzzztzzzzzb\n" +
                "2-12 x: gmfmzzrxsqbx\n" +
                "10-12 x: xxxzbxxjxxxkxb\n" +
                "3-4 v: szpvbvlvr\n" +
                "2-5 r: grqqr\n" +
                "4-8 q: mqqnvqvqqq\n" +
                "6-10 v: vdbvnvvxvvvnvvvvv\n" +
                "4-10 d: dddtdddddjd\n" +
                "3-4 l: klmc\n" +
                "10-13 k: kkbkkkvkhkvkkkkkl\n" +
                "1-3 v: vvkz\n" +
                "13-14 h: pkgffgcszgsghbcdtpm\n" +
                "11-16 c: dgccccccctchxbfm\n" +
                "8-9 b: bbbbbbbbbtb\n" +
                "1-9 h: hrnhhlphhh\n" +
                "17-18 s: ssssssssssssssssst\n" +
                "5-10 h: hhhhhzhhhhhx\n" +
                "2-7 k: dlrncbkkwp\n" +
                "3-5 k: kfqkk\n" +
                "4-8 d: ddddddddd\n" +
                "10-15 m: mmmmrmmmlpmmmrgmkmx\n" +
                "2-4 g: gsgggkm\n" +
                "7-9 l: llsllllvrzlxlrgglk\n" +
                "2-9 f: fzfbvfkff\n" +
                "13-14 p: pxppppppppppvf\n" +
                "15-17 z: nbkxkjtszptcndzdl\n" +
                "3-6 z: zzxzzhz\n" +
                "12-13 t: tttttttttttttt\n" +
                "5-10 s: pssbfsbsssnssvsb\n" +
                "9-18 c: ccxthchscjjdccvcncl\n" +
                "3-5 f: fndfqffffff\n" +
                "2-4 m: clwvcdjmz\n" +
                "7-8 b: bbbpbjbb\n" +
                "2-3 r: rbxx\n" +
                "3-8 j: jjjjjjjjj\n" +
                "5-10 v: zrwnvbrvmm\n" +
                "4-6 h: hhghhhhh\n" +
                "6-8 f: fnffzfwfgffpfc\n" +
                "5-6 q: qvqqqqkqqq\n" +
                "3-5 v: vgwvrgqc\n" +
                "9-10 p: pppphbbpphppb\n" +
                "10-12 l: rdjrcxkgflll\n" +
                "9-14 h: qwwxnhfhnfhhbhhjr\n" +
                "9-10 d: ddddpddddd\n" +
                "4-13 w: wwwwwwwwwwwwwwww\n" +
                "8-16 x: xrxxxxxxxdlxxxxxxx\n" +
                "6-10 p: pplppkpzwb\n" +
                "5-7 j: wpjjjgjjvjqjrgj\n" +
                "4-13 w: cwwswwwwwjwwdvw\n" +
                "5-6 j: jjjsjjj\n" +
                "4-5 c: ccfccqdqctllbm\n" +
                "7-13 c: bcccccccccccccc\n" +
                "4-5 p: pgptw\n" +
                "1-4 p: qpwmp\n" +
                "3-5 f: fftfff\n" +
                "2-6 m: mmhbpmjlx\n" +
                "9-13 r: zrrczrlrzqxrszrrlrr\n" +
                "2-9 w: xrszwwwdkww\n" +
                "6-14 g: qlwswsgjdlgmzvwg\n" +
                "6-8 z: zzzzzzfz\n" +
                "6-7 w: xwzsjjr\n" +
                "2-13 f: fxmfdnfffkpggz\n" +
                "1-7 d: rdnlqdplfddjdd\n" +
                "11-14 j: kjjvjjjxpjjjjjzjjjz\n" +
                "12-14 p: gpppwvmqpfpptpfppkpc\n" +
                "6-11 k: kkkkkhkknkkkkkgk\n" +
                "2-6 m: swpgmf\n" +
                "1-3 x: sxzqnxxv\n" +
                "12-18 n: nnnnlnnnnnnnnnnjnxnn\n" +
                "3-4 p: pppq\n" +
                "8-9 v: vvvvvvvpv\n" +
                "6-9 l: ltsldwtlhll\n" +
                "11-14 x: xxxxlxxhdtxxxxxsxx\n" +
                "4-5 q: qsqvqvq\n" +
                "5-6 b: sbbbbt\n" +
                "10-13 l: lllllslllrllll\n" +
                "1-5 m: zmmmmmmm\n" +
                "2-10 s: ssssssssss\n" +
                "5-8 r: qqcsbjcrljvksc\n" +
                "11-15 n: bndcnknnxnnnnnbn\n" +
                "14-15 v: tvvvvvvvvhqwvvv\n" +
                "2-3 s: jsvcsb\n" +
                "12-15 d: mddddfddddlxddddd\n" +
                "12-18 w: wwznwcgwwwwwwhwwgwgw\n" +
                "2-9 v: dxlvvlvqg\n" +
                "2-5 h: njpsxr\n" +
                "11-13 m: rmmmmmmqmmzmtmm\n" +
                "4-8 m: smmmmmmm\n" +
                "3-10 j: ngwtkjfrjjtrxfnvj\n" +
                "2-3 p: ppwwpp\n" +
                "3-5 c: cbmcncnqc\n" +
                "11-13 m: mmmmmmmmmmcmm\n" +
                "4-14 g: gggggggggggggxg\n" +
                "2-4 b: bbfb\n" +
                "16-19 p: ppppppppcppdpppmppwp\n" +
                "10-12 g: gghgxgkvggrggrg\n" +
                "1-8 b: wjjqktjbbfkdz\n" +
                "8-11 c: cqccdcncfcccnc\n" +
                "2-10 z: qzvlqltzns\n" +
                "3-7 p: kgpmpzpbx\n" +
                "1-6 m: mxmdmlmmzmmmmmmmmm\n" +
                "1-7 r: rrrrrrrrrrrc\n" +
                "8-10 h: whhhqhhhjjhnch\n" +
                "6-10 x: xwxxxxkpxdkdnxvh\n" +
                "10-12 z: zzzzzzkzzpzzzzz\n" +
                "1-12 s: dssssssssssds\n" +
                "4-7 f: fvzbfcf\n" +
                "5-6 w: fwwxfwmswxkd\n" +
                "14-15 g: gggggggzgggggfhg\n" +
                "6-7 j: jjjjjnb\n" +
                "1-6 v: vcgksvnrbgsvkrwsc\n" +
                "6-15 w: wkvwwwpqwwwbtwxvhw\n" +
                "8-9 m: smmmmmmmmm\n" +
                "14-15 r: rrjrlrrrrrrrrzbr\n" +
                "3-8 w: tjqncxsnqkdpwzm\n" +
                "4-5 k: kkkkk\n" +
                "8-11 z: zzzzzzpzzxzzkzglzrz\n" +
                "5-6 k: kkkktzk\n" +
                "18-20 w: wwwscwwwwwwwwwwwwgws\n" +
                "1-12 z: dsfxzctdzzjxbt\n" +
                "14-15 q: qqqqqdqqqqqqqqq\n" +
                "7-10 r: rrxrrqrrxcbr\n" +
                "1-13 d: fmgjzgqhdhddd\n" +
                "4-6 g: mnggxttn\n" +
                "6-7 v: gwtmscl\n" +
                "11-14 g: gggnmgggggjggcgggrgg\n" +
                "17-18 k: gcslskskkkwkwkklkk\n" +
                "14-16 r: rrrrrrrrrrrrrbbrr\n" +
                "13-15 s: sjsxszssgfssdgwsbbsp\n" +
                "1-9 d: dddddddddddd\n" +
                "1-13 j: mnjjzckxzjjdj\n" +
                "1-2 j: hwrqjxxcj\n" +
                "6-7 z: fzzzwxnnrg\n" +
                "2-10 x: wxnqjddpxxpxw\n" +
                "3-10 s: srvvssdcvzfn\n" +
                "3-11 w: gwwwmwvwwww\n" +
                "3-4 q: qnqs\n" +
                "11-12 d: dddqdddzdrddddd\n" +
                "2-15 l: wldlltxhrwzzlhz\n" +
                "4-7 g: vgsgkfgmc\n" +
                "7-9 t: jdsltcgttdttd\n" +
                "9-10 q: xvqjqqqwqqqqqpqq\n" +
                "6-9 b: bbkbnbgbbb\n" +
                "2-5 t: ttcjtbkb\n" +
                "7-8 r: rdrrqrnrrrrrvp\n" +
                "2-4 f: pnfqfffvpfffffhbffv\n" +
                "10-12 z: kzzzzzzzzrzpzszz\n" +
                "4-5 m: tmmgxlm\n" +
                "3-4 k: kwhhk\n" +
                "1-11 h: hhhndhhfhvhchmmqhz\n" +
                "6-9 m: lmmmmmmmtmmm\n" +
                "1-5 d: dwdkd\n" +
                "5-6 d: dddddq\n" +
                "7-9 j: jjjvgvmjdjbjj\n" +
                "3-6 w: gwzhpjwkg\n" +
                "10-11 h: hhlmftlhkhhnh\n" +
                "8-20 h: hhgnchpthzhhhhqqwhcz\n" +
                "6-7 s: sssssgfs\n" +
                "3-11 g: jfgqgbvqppjn\n" +
                "5-6 d: ddqkmbd\n" +
                "14-15 h: hhhhhhhhhhhhhphhh\n" +
                "12-13 l: fwkwphdlwmfwg\n" +
                "3-4 z: pmbncwz\n" +
                "3-4 w: lgwv\n" +
                "3-4 s: sshs\n" +
                "2-7 z: zzflznzzzlzl\n" +
                "1-2 k: klbjvbwpkkptb\n" +
                "17-18 r: rrrrrrrrrrrrrrrrlrr\n" +
                "7-8 l: mlqgltml\n" +
                "9-14 l: llljlllxllllvl\n" +
                "5-13 b: bbbbtbbbbbbbfbbbg\n" +
                "7-10 d: cddlddgdqkld\n" +
                "4-6 q: kqqqqq\n" +
                "5-11 r: rrrvrrrsrjrr\n" +
                "7-10 t: tttgtltttbt\n" +
                "13-14 h: hhhhhqhhhhhhndh\n" +
                "3-4 s: dsss\n" +
                "6-12 w: jwwtxwwwkkwbw\n" +
                "7-8 v: cvvgnvvv\n" +
                "12-16 q: qqqqqqqqxvqqqrqqqq\n" +
                "6-11 z: zzkvzvzzzxzzzz\n" +
                "4-9 s: lcrvsssmfs\n" +
                "6-13 c: ccccpdcbcbcgdcccgdcc\n" +
                "7-9 q: qpqqqqqqhq\n" +
                "1-10 k: kwfkkxrkwhtmkwknkx\n" +
                "9-20 x: dxzrxxxsxxxjxxsxdczx\n" +
                "15-16 c: ckcccdccccccgccdcccn\n" +
                "2-7 s: sscxswskxhchxpfs\n" +
                "2-3 h: hhlh\n" +
                "2-6 p: ppppppp\n" +
                "6-8 r: ztmrsjqtrk\n" +
                "1-2 r: drsdvpmzdn\n" +
                "6-7 v: vqvvvgp\n" +
                "5-6 g: gggggg\n" +
                "3-7 d: tfkddmjzjgdxzlkd\n" +
                "16-17 b: bbwbbbbbbbbbbbwbt\n" +
                "2-11 b: hbrwqqhkcrbbvmx\n" +
                "5-11 f: ffffqfffffffff\n" +
                "2-5 n: nnwhn\n" +
                "8-11 j: jxjsjjmjkjkjhjx\n" +
                "1-3 h: hhhh\n" +
                "5-12 t: pttttszttwvlt\n" +
                "7-8 q: mqqqqqqqtkq\n" +
                "7-10 z: xzzzzzdzzzzzzzz\n" +
                "6-7 l: ljzqklhmm\n" +
                "3-5 k: bkkkrk\n" +
                "6-8 x: xxxxxlxcxxxbx\n" +
                "6-7 j: jjqjcpjfjj\n" +
                "8-9 l: cwmllhslwv\n" +
                "14-15 z: zzzzzzzzrzzzzcz\n" +
                "11-12 f: sfccmxxffsfg\n" +
                "5-6 q: qqqqqqqq\n" +
                "12-15 t: tttttttttttttttt\n" +
                "7-12 q: pqwsnhqfzdtqxd\n" +
                "4-5 b: fbcbb\n" +
                "5-7 t: tttstft\n" +
                "2-4 h: vjmr\n" +
                "4-6 r: rrfrprr\n" +
                "18-19 x: xxkxxxxxxxxxxxxxxxxx\n" +
                "2-4 k: qklkc\n" +
                "3-6 s: svjsrs\n" +
                "14-15 j: pjjjhjjjjjjdjgj\n" +
                "2-15 l: lhllllllllllllwlll\n" +
                "2-7 q: qvqqgsq\n" +
                "2-6 z: zzlzzzn\n" +
                "8-15 p: pppppppspppzppgp\n" +
                "3-4 l: kfzbl\n" +
                "9-12 w: hqjwwtdwwlwwmw\n" +
                "3-4 k: lghgg\n" +
                "3-5 k: khgzkk\n" +
                "2-10 r: rrsjlmrsrr\n" +
                "2-5 j: jjjjj\n" +
                "10-12 j: jfgzbdbjwhjjjf\n" +
                "1-4 f: ffff\n" +
                "9-10 j: jjjwjjwzgtcjzj\n" +
                "1-6 m: mmmmmq\n" +
                "5-6 h: hhwhph\n" +
                "3-6 w: wwpwwz\n" +
                "5-6 q: qqqkcb\n" +
                "8-9 f: ffffffxrff\n" +
                "13-14 m: lqvpbrhgmxmkgj\n" +
                "4-6 q: pqqxqk\n" +
                "7-11 b: mbbnsvbbjbbmb\n" +
                "17-18 q: qqqqqqqqqqhqqqqqqqq\n" +
                "3-12 w: qzcwxswwzvwzb\n" +
                "10-11 l: llllllllxxs\n" +
                "1-4 c: bvcch\n" +
                "11-13 s: svssqfvssshst\n" +
                "6-7 l: lllllrl\n" +
                "5-8 n: nhqkfnggnpkbhpgntlht\n" +
                "1-14 g: pgrdgjggggpggc\n" +
                "12-16 n: hlnhkxpnnsfctsnq\n" +
                "6-8 c: cccftqcfqc\n" +
                "1-5 f: fbfff\n" +
                "1-15 t: mttptftctttptttt\n" +
                "6-11 t: cxtttnnfttt\n" +
                "7-11 h: hsrfjswhhhhhhhhc\n" +
                "12-13 b: bbbbbbbbbbbnfbvb\n" +
                "12-13 x: lzvxjxxxcxxxq\n" +
                "12-13 p: ltwhhhqvdjptbsw\n" +
                "7-9 z: zzzzzztzn\n" +
                "4-5 g: ggqlgg\n" +
                "8-10 r: rbqxwzfhlzt\n" +
                "3-5 g: grhgk\n" +
                "14-19 z: zrzzbzztszpzvzbdfzm\n" +
                "7-11 d: tdjbcdpdddb\n" +
                "3-7 j: jpqjjjj\n" +
                "1-2 m: mcxklcmmws\n" +
                "7-8 r: drqlcrfqrgrrxrrg\n" +
                "1-5 g: kgngw\n" +
                "8-10 r: wrrbfrrrpntjrrrgrr\n" +
                "1-4 s: sstf\n" +
                "3-7 b: fnjnpmfjlwb\n" +
                "2-5 s: pwjkj\n" +
                "9-11 t: tbtbtrsrfzntwqq\n" +
                "13-16 m: mmmmmmmmmmmmmmmmm\n" +
                "13-18 b: bbbbbbbpqlbbbtbtpxb\n" +
                "9-11 w: wclwwwrwwwkhww\n" +
                "7-13 b: bbbbbbbwbbbbb\n" +
                "8-12 t: sxlwtttttnhn\n" +
                "4-7 q: kmdqxcqswqw\n" +
                "3-4 r: rjrr\n" +
                "4-6 m: mdmdmmmm\n" +
                "6-17 h: kjrkchhnfhqqcrmhhhdh\n" +
                "6-9 j: vjjgcjjjpdj\n" +
                "7-9 x: xxxxsxxxxx\n" +
                "8-16 j: jjjjjgjnjjjjjjjczd\n" +
                "6-8 t: tttttttd\n" +
                "7-17 s: ssmsspvsssspssssfssl\n" +
                "3-10 f: cgffsqxhdmrvdf\n" +
                "1-3 f: wfpf\n" +
                "11-12 k: kkkkkkkkkkfqk\n" +
                "12-15 s: cxghswzsbttmvpscr\n" +
                "3-4 n: nnkn\n" +
                "7-17 w: wwlwnxwxwwswwwwwg\n" +
                "3-10 h: hhvhhhrhhhfghhcn\n" +
                "10-11 l: lllxlllllllsl\n" +
                "5-7 d: ddbddtddv\n" +
                "5-15 g: ggtggqggggzggggwggv\n" +
                "2-10 r: mrpdmtrzsrngstsr\n" +
                "9-15 t: bsbptttttqwzmmtgbgm\n" +
                "8-10 q: qqqqqqqqqqq\n" +
                "6-9 h: hlrbcsnhh\n" +
                "12-17 f: ffkjfffffffnftfmf\n" +
                "11-12 s: ssssssssssss\n" +
                "9-15 k: hpkskfkkfkkkkbkk\n" +
                "8-18 b: bbbbbbdbbbbbbjbbjw\n" +
                "2-14 p: nppppkkppppppw\n" +
                "11-12 s: sxhtlrtnbgss\n" +
                "8-10 q: lnwqqqqqqsqhgqgbq\n" +
                "2-3 l: llll\n" +
                "14-17 d: gdddtlfmrdscgsqcmkm\n" +
                "5-8 w: tmmskwpq\n" +
                "16-17 b: cbbbpzbbrrbnkbbbbgj\n" +
                "14-17 b: bbbjbbbbbbbxbvbdszbb\n" +
                "9-10 q: qqqqqtqqqqr\n" +
                "5-6 t: ctgttztrtn\n" +
                "2-3 f: gcfgw\n" +
                "3-8 d: ddzddddsddddddd\n" +
                "15-16 g: ggggggjggggggggg\n" +
                "4-10 m: mcmmmmmmmmmvmmmm\n" +
                "11-15 p: ptppxjppppmkgpvdp\n" +
                "12-13 n: nnnnnnnfnnnrn\n" +
                "1-7 t: tnbwtttmtt\n" +
                "1-14 c: ndncvjbkcmcjplcp\n" +
                "1-2 f: fffh\n" +
                "14-17 t: llzkwltkmdntwndqs\n" +
                "4-7 w: bffzzwdwtkwwv\n" +
                "4-8 p: zpbpqpppxpb\n" +
                "8-14 n: fdnnznhnnlhmtn\n" +
                "7-14 l: vltrjnzhplkshlt\n" +
                "1-2 d: ddbhsjtv\n" +
                "2-10 d: dddddbzrdrdd\n" +
                "4-10 p: pkppshsfmp\n" +
                "10-11 g: gmgggzvzmgjgggzqxggd\n" +
                "2-4 j: fjvjjqf\n" +
                "5-19 h: cstkhhrctkxhhsfzpph\n" +
                "6-16 s: sssssssssssssssks\n" +
                "17-18 v: vvvvvvvvsvvvvvvvtv\n" +
                "2-5 j: zjjjjj\n" +
                "2-3 r: xrrrqlxl\n" +
                "17-19 c: cccrcccgcwcchccccdcc\n" +
                "7-14 l: lllllllllllllcsl\n" +
                "12-14 p: jlmhpjgdzjkpnbmnbk\n" +
                "17-18 n: nnnnnnnnnnnnnnnnqv\n" +
                "8-10 b: lqzrtbzbrb\n" +
                "8-11 x: xgxxfxxxxkxx\n" +
                "5-9 x: xxxsnxnxk\n" +
                "2-11 t: stxbxwssmgthttx\n" +
                "6-13 t: ktbktrtqcnlrgtvtwt\n" +
                "10-12 q: qqqqqqqqqrqq\n" +
                "14-15 q: znptzmgllrfrqrf\n" +
                "2-13 f: ffffffcffffff\n" +
                "9-10 h: hrbhnhhhhhhhh\n" +
                "8-14 k: lskskkkfzkkkkmkkm\n" +
                "1-3 g: kbmswhmghvwvnwxzzk\n" +
                "2-4 v: vttv\n" +
                "2-3 h: qhhmhghbh\n" +
                "6-13 t: ttgtttttktttdttt\n" +
                "7-9 v: vvrrvvvvvv\n" +
                "5-6 z: hcfwdr\n" +
                "5-13 g: sgmgggcggggggjrggggk\n" +
                "10-14 k: kzkkkkkkdskkktkkk\n" +
                "1-2 j: ptjj\n" +
                "4-11 b: xnbbbbnbbbb\n" +
                "14-16 b: bbbbbbbbbbbbbkbc\n" +
                "4-12 w: mwrwrcpwkpzwxrj\n" +
                "5-6 l: qlndzlcvw\n" +
                "1-2 s: ksxk\n" +
                "4-5 p: spgwql\n" +
                "7-10 j: ljjjjvxjhzjjjjrj\n" +
                "6-14 f: ffffffffffffff\n" +
                "11-15 d: ddddddddddzdpdn\n" +
                "3-5 t: ttmtz\n" +
                "6-7 x: kxvxxxx\n" +
                "3-6 m: mhmklm\n" +
                "4-8 h: bnhjhphgqxphpnthh\n" +
                "3-4 w: gwpq\n" +
                "10-13 t: ttvttjhttcttrtthtb\n" +
                "1-5 f: ffffg\n" +
                "6-14 v: rtjjvpbvnvjwlvktvvf\n" +
                "8-9 n: nnknnnxmnnn\n" +
                "9-10 v: vvsvvsvvqcvvpp\n" +
                "9-11 x: xxxxxxxxxwl\n" +
                "3-6 h: bwqxnrhkhhwhhh\n" +
                "4-8 l: lvllrlcf\n" +
                "1-2 m: gtrm\n" +
                "2-4 z: zzzz\n" +
                "6-7 j: jjjjjjj\n" +
                "15-16 g: sggggggggqgclgggmggw\n" +
                "7-9 v: dvmskjsczkvjcpsv\n" +
                "3-11 d: hmdrdfdqrddzdddjdd\n" +
                "7-9 m: mmmwfmmmtmm\n" +
                "6-8 x: lxsbxmlx\n" +
                "3-5 q: qqqxq\n" +
                "5-10 n: nnnnznnnnrn\n" +
                "4-6 m: zmmbzg\n" +
                "10-11 c: cpdndvlfltc\n" +
                "2-4 k: kzkkk\n" +
                "1-14 m: jmmmmmzmqtmsmmnmm\n" +
                "3-13 h: gwhhrlbstldmh\n" +
                "2-5 l: rrlhdqkzst\n" +
                "1-6 s: sqgsjs\n" +
                "3-4 h: hhgpb\n" +
                "11-16 l: llllllllllllllwkllll\n" +
                "7-11 j: gjjjtvhjjpj\n" +
                "14-15 h: hjjvmbhfjhhxkbh\n" +
                "1-2 t: rwxgz\n" +
                "13-18 p: pppppppppppppppppppp\n" +
                "1-14 x: xxrxxjxhxxxxxxbxxx\n" +
                "4-6 b: fbzsbpbbb\n" +
                "12-16 j: fjjgmnjwbvhjzzzs\n" +
                "6-7 m: mmmmmtq\n" +
                "12-16 n: nnmnnpnnnnnknqxkjnjn\n" +
                "5-8 w: wmwwwwpwlwllzwkcw\n" +
                "7-10 q: gbpsnqwqfm\n" +
                "10-13 x: vxxxxxxxxxdqnxx\n" +
                "7-12 q: qqqqqqqqqqqqqqq\n" +
                "1-2 n: snnn\n" +
                "6-10 l: lljllklllwp\n" +
                "3-4 b: bsnjzbb\n" +
                "13-14 g: tggztfgdggngmglgg\n" +
                "6-16 l: bkcwjlwcnfwthlll\n" +
                "8-11 s: sssssssvsss\n" +
                "3-4 k: xmthtrcx\n" +
                "7-8 h: wpmjhbgg\n" +
                "4-5 p: pcpkvp\n" +
                "14-15 s: ssrssssssssssjs\n" +
                "14-15 x: xxxzxxgxxtxxxxqx\n" +
                "6-7 m: nwmfmxmm\n" +
                "6-8 k: hsknkmvhkgkkfzkjf\n" +
                "4-5 s: sssms\n" +
                "7-9 g: gfgqldxgxdjzglcgg\n" +
                "10-11 k: ckkthkzpdrfv\n" +
                "1-14 p: jptppkcppjpppppppp\n" +
                "10-11 x: pxkccxpxdsq\n" +
                "2-8 x: xsgxxxxvgxxk\n" +
                "6-14 j: jjjjjzjjjjjjjtjjjj\n" +
                "7-10 x: rxxnxrzgxxd\n" +
                "6-12 g: dmgggpgggwczggghggm\n" +
                "3-6 h: hdhjhhhhchh\n" +
                "11-12 r: zrrkcrrrrrlh\n" +
                "7-9 v: vhqvlvwvzqwqvrxvjnf\n" +
                "1-5 r: rvmjr";

        String[] passwordsWithParams = data.split("\\s*\\n\\s*");

        int counter = 0;

        for (String pass : passwordsWithParams) {
            String[] params = pass.split("[-: ]");

            if (checkIfCorrect(Integer.parseInt(params[0]),Integer.parseInt(params[1]),params[2].charAt(0), params[4])) {
                counter++;
            }
        }

        System.out.println(counter);
    }

    public static boolean checkIfCorrect(int min, int max, char character, String password) {

        long count = password.chars().filter(ch -> ch == character).count();

        return count >= min && count <= max;
    }

}
