package com.adventofcode;

import java.text.Collator;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public class d6t1 {


    public static void main(String[] args) {

        String data = "fekdcbayqxnwvh\n" +
                "fycwqktvxandeb\n" +
                "kqbafvcxyewrdn\n" +
                "akwqcvenxfydbs\n" +
                "ewbaxdcvnkyfq\n" +
                "\n" +
                "timjneyhbvxkfagdpzrous\n" +
                "gsumijvxoheptbafnkyzrd\n" +
                "yxtbnupramvdezhkfojsig\n" +
                "soaruhxnpiemjvytzbfdkg\n" +
                "vfanlgjoiskzmubtxhceyprd\n" +
                "\n" +
                "dhgabzfspkltq\n" +
                "pflzsbtaxhqdkg\n" +
                "kzpbfgasthldq\n" +
                "\n" +
                "xeu\n" +
                "uoe\n" +
                "tnpeox\n" +
                "e\n" +
                "vrdzwglecbk\n" +
                "\n" +
                "nucwl\n" +
                "hnmx\n" +
                "fqv\n" +
                "\n" +
                "kfubtzpovrdlw\n" +
                "vdjmblrztpkosfg\n" +
                "kavpdbgfzreol\n" +
                "qpdzfrvokibcy\n" +
                "\n" +
                "yhknrqpubeolzixtvsj\n" +
                "tlysdjzovxhnuqreimk\n" +
                "\n" +
                "bclpmatw\n" +
                "btqmcw\n" +
                "cvwtbm\n" +
                "bmwct\n" +
                "ctmwb\n" +
                "\n" +
                "qmo\n" +
                "oqm\n" +
                "\n" +
                "su\n" +
                "s\n" +
                "s\n" +
                "s\n" +
                "s\n" +
                "\n" +
                "ztfmocgiesxdq\n" +
                "fpjmthksidlbo\n" +
                "\n" +
                "smzbn\n" +
                "bmnzes\n" +
                "skzmnb\n" +
                "mbszn\n" +
                "\n" +
                "kibmrznqcyladupv\n" +
                "umnbkdpievlqcyar\n" +
                "idavpbmnrklqucy\n" +
                "\n" +
                "favynhqocijkmtbzsrulp\n" +
                "ycbzrmkuvlhnpfqsitjao\n" +
                "ujbomprktafvliqhycnzs\n" +
                "nymjkczihqbpfvutosalr\n" +
                "\n" +
                "tdev\n" +
                "vh\n" +
                "wva\n" +
                "va\n" +
                "gzv\n" +
                "\n" +
                "d\n" +
                "d\n" +
                "d\n" +
                "\n" +
                "ejrmqwg\n" +
                "merjguw\n" +
                "jmreugw\n" +
                "mjrgwtie\n" +
                "\n" +
                "wxiqgpu\n" +
                "guxqiwp\n" +
                "puigxqw\n" +
                "pugqwxi\n" +
                "\n" +
                "ealugrzsvhpxfmjdbqknoy\n" +
                "doyhvplkjqarnbeutxsgfmz\n" +
                "uhvxjaklmzoyqdbegrpfsn\n" +
                "\n" +
                "iv\n" +
                "os\n" +
                "\n" +
                "o\n" +
                "amtle\n" +
                "n\n" +
                "npz\n" +
                "\n" +
                "vbfxystq\n" +
                "knsxyqubtvf\n" +
                "\n" +
                "t\n" +
                "p\n" +
                "p\n" +
                "o\n" +
                "\n" +
                "xtz\n" +
                "ptz\n" +
                "ftx\n" +
                "ujt\n" +
                "tp\n" +
                "\n" +
                "rs\n" +
                "qdfan\n" +
                "mkpz\n" +
                "\n" +
                "idewynukmzac\n" +
                "yacfmdwuizke\n" +
                "ieuamdczkywf\n" +
                "iczwymuekad\n" +
                "adwekumyciz\n" +
                "\n" +
                "agnq\n" +
                "gn\n" +
                "gno\n" +
                "gni\n" +
                "vkmnxug\n" +
                "\n" +
                "ftlyhuvaj\n" +
                "xsribwknlgmt\n" +
                "\n" +
                "a\n" +
                "nay\n" +
                "a\n" +
                "a\n" +
                "\n" +
                "leq\n" +
                "q\n" +
                "qj\n" +
                "\n" +
                "sxrwi\n" +
                "isrwx\n" +
                "wrsix\n" +
                "iwsvxjr\n" +
                "rixwbs\n" +
                "\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "p\n" +
                "\n" +
                "unvlyxripzbmaedwjsfqth\n" +
                "uvefyibspxrzjdlwtqhnam\n" +
                "hnbapqzflsvxreiutmydwj\n" +
                "nwdefhtzrxuqpsvljabyim\n" +
                "razbwymsdfpnlutqxveijh\n" +
                "\n" +
                "zfihqcvwdbsm\n" +
                "sufwpahczlbvd\n" +
                "\n" +
                "tqjanyicszeodpmk\n" +
                "ljmtwvkrcfghdqbu\n" +
                "\n" +
                "ydxnthpazbskufcq\n" +
                "txymsjdfhwuqbz\n" +
                "vhyuqsfjbxdrtzg\n" +
                "\n" +
                "smyvegtwiu\n" +
                "imyqtuesv\n" +
                "idrluzhjatkvpc\n" +
                "\n" +
                "pzacglju\n" +
                "pzulcagj\n" +
                "jcalgupz\n" +
                "\n" +
                "rgzbvefacsw\n" +
                "vafbrezcw\n" +
                "wegjvrczfqba\n" +
                "zwrvabpfce\n" +
                "rlhekwzyfbacovm\n" +
                "\n" +
                "hfqu\n" +
                "fq\n" +
                "\n" +
                "kywvrsxgiojp\n" +
                "xosvigpkwyjr\n" +
                "irwkjfvmxpsyog\n" +
                "pvxyrwiksjgo\n" +
                "\n" +
                "ynebghqmrkcjlpiuftdoaz\n" +
                "reaqjoyngdbiltkmuphcf\n" +
                "ynobfdgluriphskejcqtam\n" +
                "\n" +
                "uac\n" +
                "ca\n" +
                "\n" +
                "fmxawgkrin\n" +
                "xfrnbigok\n" +
                "sfighjeckrux\n" +
                "girxkfl\n" +
                "gaxirnfk\n" +
                "\n" +
                "smoyaxbku\n" +
                "uobkxysam\n" +
                "kyszxumojba\n" +
                "\n" +
                "uocvgjr\n" +
                "hjponwcuzg\n" +
                "\n" +
                "fobhkeascqluwrzm\n" +
                "hzcolfipysnrjaguwkeq\n" +
                "ezwlhkcfsoxqrua\n" +
                "\n" +
                "blnosjgezuqcrvxwm\n" +
                "cmeznoglqxubwjrsv\n" +
                "zxnqvwoubpremsjcgl\n" +
                "umxrlsgqoczwbvnej\n" +
                "cuxanesjkivzrmlboqgw\n" +
                "\n" +
                "dewtyuqjlv\n" +
                "ucvazfm\n" +
                "\n" +
                "kbm\n" +
                "imltbj\n" +
                "\n" +
                "ydqnxlmbouvaztcg\n" +
                "vhrkwxjzfnpisye\n" +
                "\n" +
                "jqeadkcibtgflsz\n" +
                "ltbxqifjedsawkzcg\n" +
                "zdfqgkijestcl\n" +
                "jczfqdektlsig\n" +
                "scdgufyjeizlkqt\n" +
                "\n" +
                "w\n" +
                "w\n" +
                "w\n" +
                "w\n" +
                "s\n" +
                "\n" +
                "wygptc\n" +
                "ygctpw\n" +
                "gcptyw\n" +
                "tpycgw\n" +
                "\n" +
                "xaqicwhtdpvk\n" +
                "aixdcpkzhvqwt\n" +
                "qkcdhxpwaivt\n" +
                "\n" +
                "wt\n" +
                "xtrowm\n" +
                "wt\n" +
                "wt\n" +
                "tw\n" +
                "\n" +
                "sncq\n" +
                "cus\n" +
                "\n" +
                "zehxb\n" +
                "txe\n" +
                "exuma\n" +
                "exz\n" +
                "\n" +
                "epjgfknhvuwmr\n" +
                "nkwrmfhjegp\n" +
                "rjkpynefgmwh\n" +
                "ehfprjkgndmw\n" +
                "mewkfdnrgjhp\n" +
                "\n" +
                "hgyc\n" +
                "kgc\n" +
                "ghc\n" +
                "cgxjzl\n" +
                "\n" +
                "evsloum\n" +
                "leosvmu\n" +
                "mejvuzoxdsl\n" +
                "evmolsu\n" +
                "\n" +
                "fugckqhymrxbtvdpnose\n" +
                "beyorulcqxgdkzafh\n" +
                "\n" +
                "s\n" +
                "s\n" +
                "sq\n" +
                "\n" +
                "wtjfgezdhsxckibrqyunvpo\n" +
                "uaonrpkmidbgftwlsjz\n" +
                "\n" +
                "mrylewxsgvfodhu\n" +
                "sfdxoyghwlrvmu\n" +
                "dungfohvlwrxsym\n" +
                "ulmsoghvxfrwdy\n" +
                "uoifgdlwrsvymhx\n" +
                "\n" +
                "tbg\n" +
                "btdg\n" +
                "tbg\n" +
                "tgb\n" +
                "btg\n" +
                "\n" +
                "pukht\n" +
                "huk\n" +
                "fhkqu\n" +
                "hykcfu\n" +
                "hedvmgubsk\n" +
                "\n" +
                "dxycvosnr\n" +
                "xcsdyrgmapf\n" +
                "qoyrsxdc\n" +
                "uedsxtyrc\n" +
                "ucdrsbxy\n" +
                "\n" +
                "m\n" +
                "xz\n" +
                "m\n" +
                "\n" +
                "gcjsybuhrotm\n" +
                "dojcsubhprt\n" +
                "\n" +
                "opmgsudhej\n" +
                "mjceogdsuhp\n" +
                "djpgmoushe\n" +
                "jgeptsluhfomakdvyq\n" +
                "\n" +
                "jugocetyrzwfbhp\n" +
                "ipvqwcozxbsdu\n" +
                "gybprkmznowultcaj\n" +
                "\n" +
                "ipcau\n" +
                "n\n" +
                "\n" +
                "juzmidp\n" +
                "iudjp\n" +
                "digjups\n" +
                "pajiud\n" +
                "\n" +
                "zxnugrosjvlcphwmqbdyt\n" +
                "bvtlmqnudzrjwysxcohagp\n" +
                "tdxhyuwemcvbrpzgnoqfjls\n" +
                "\n" +
                "hoefmguvxyiazwcpbrjk\n" +
                "umlbagzxeowthjfpik\n" +
                "hmxeziglfbwjup\n" +
                "jgxbspifzwqhneum\n" +
                "\n" +
                "mgvupsk\n" +
                "ezwcui\n" +
                "\n" +
                "adczjnguyq\n" +
                "ygnujdacqz\n" +
                "\n" +
                "ohricgqjfu\n" +
                "rqgucfhoji\n" +
                "\n" +
                "vygwkszidxqa\n" +
                "onxkejczsguywqv\n" +
                "stvzbqypwmxkg\n" +
                "\n" +
                "ydjm\n" +
                "fpbustykx\n" +
                "yrq\n" +
                "ry\n" +
                "\n" +
                "vjphn\n" +
                "npvhj\n" +
                "phvnj\n" +
                "\n" +
                "bryndzmekui\n" +
                "oathqpcv\n" +
                "\n" +
                "yczewurklaxnfdhoqbt\n" +
                "rlyhawcdunqeofxkzbt\n" +
                "lhbsqfkxctyonwrdzuea\n" +
                "zltnhdkqybaxufoerwc\n" +
                "\n" +
                "cjwarkog\n" +
                "joawgrkc\n" +
                "wcjgkrao\n" +
                "wrcjogak\n" +
                "coerwgsajk\n" +
                "\n" +
                "umwjqsetdg\n" +
                "sjwmet\n" +
                "jbteyhownvsaxm\n" +
                "dmuspcztjrew\n" +
                "\n" +
                "xtswpc\n" +
                "eahncvzqxkgmo\n" +
                "lcixybdrsuft\n" +
                "\n" +
                "pcrfwszodmqnj\n" +
                "vrcylgb\n" +
                "iruc\n" +
                "\n" +
                "bqigzouxryndpa\n" +
                "jaixybnro\n" +
                "oabixhnjry\n" +
                "\n" +
                "pbznr\n" +
                "xrb\n" +
                "bdntx\n" +
                "qecbyi\n" +
                "\n" +
                "zbvhxyfm\n" +
                "vxmbyfpz\n" +
                "vbxzmyfh\n" +
                "\n" +
                "nfcqwuhsrxojk\n" +
                "jrqvokfscnxuh\n" +
                "nxqiaulkrojszchyf\n" +
                "\n" +
                "dkwqfb\n" +
                "wd\n" +
                "hwd\n" +
                "nhwd\n" +
                "dnw\n" +
                "\n" +
                "vjtpxorsdyzbwhqi\n" +
                "kirdlmofpnectxqwuz\n" +
                "\n" +
                "ynzxtvqogrdhwl\n" +
                "yhdjomktn\n" +
                "\n" +
                "hqwn\n" +
                "hnwq\n" +
                "hnqw\n" +
                "hwnq\n" +
                "\n" +
                "gosxz\n" +
                "xog\n" +
                "gfomxa\n" +
                "ogxd\n" +
                "\n" +
                "wctesuhxonyl\n" +
                "oxwhtecynusl\n" +
                "cslwxehupyton\n" +
                "\n" +
                "pr\n" +
                "spr\n" +
                "pr\n" +
                "pr\n" +
                "\n" +
                "maqfseovdhzj\n" +
                "sqodparevimfzjl\n" +
                "dxosqmafejvz\n" +
                "dqzojehfasvm\n" +
                "\n" +
                "awsicurgfmxeqjylnvktbd\n" +
                "dywmreaitvjgcnbklxs\n" +
                "\n" +
                "wmvbnqtxuriz\n" +
                "hbuwefypzlkadq\n" +
                "\n" +
                "asjcpwml\n" +
                "lcasmjpw\n" +
                "ajspcmwl\n" +
                "cmslwjap\n" +
                "\n" +
                "unkrl\n" +
                "n\n" +
                "ny\n" +
                "yan\n" +
                "nv\n" +
                "\n" +
                "zrjwsxduie\n" +
                "jswxrziunde\n" +
                "xrujwhsidze\n" +
                "\n" +
                "qnl\n" +
                "unc\n" +
                "xhtdjbvf\n" +
                "omauis\n" +
                "\n" +
                "wxvoqihatseg\n" +
                "setwqgi\n" +
                "ewgstqci\n" +
                "fetwqgis\n" +
                "wqtfgkiesd\n" +
                "\n" +
                "vmpikgfsarbnxqudwjtoh\n" +
                "bdovpatjgnxkqufsihmrw\n" +
                "bjhnrtaokxudmfqpigwvsc\n" +
                "kaqbvihwmsnxjpgrtoufd\n" +
                "fmabtdgkuhxpwrivsoqnj\n" +
                "\n" +
                "eazsitkjronml\n" +
                "otmrenjakzsi\n" +
                "samrojenitzfk\n" +
                "tkzenmrjoais\n" +
                "tszkioaejrnm\n" +
                "\n" +
                "r\n" +
                "rbq\n" +
                "r\n" +
                "r\n" +
                "\n" +
                "lwbrfsuahoq\n" +
                "yjawifugdtrvs\n" +
                "rfbaswu\n" +
                "cfsarlknupw\n" +
                "\n" +
                "ist\n" +
                "ay\n" +
                "kc\n" +
                "cu\n" +
                "kd\n" +
                "\n" +
                "mbku\n" +
                "bkva\n" +
                "\n" +
                "sxktwmyfaldbn\n" +
                "ymkbnfpdltx\n" +
                "xbyftnmkdl\n" +
                "dlkfetbimxycn\n" +
                "\n" +
                "cjru\n" +
                "rcju\n" +
                "rjucl\n" +
                "kcjrum\n" +
                "auzcjrtn\n" +
                "\n" +
                "vkinfzqbrled\n" +
                "rinldvbqfze\n" +
                "rqizebfvldn\n" +
                "aciqrfbsnelvxdz\n" +
                "\n" +
                "ig\n" +
                "ig\n" +
                "gi\n" +
                "gi\n" +
                "\n" +
                "rskzxocuq\n" +
                "kcovqsnztur\n" +
                "skzocrnyuq\n" +
                "vourxysqzkc\n" +
                "opescqukrhjz\n" +
                "\n" +
                "i\n" +
                "u\n" +
                "\n" +
                "xqfviycpuzjbwkn\n" +
                "lnxbfkpcyqdawm\n" +
                "xofypnwkbcqv\n" +
                "wbvxcfkqtnpry\n" +
                "bnoixpfqgkcwy\n" +
                "\n" +
                "ziwlofkdgpc\n" +
                "qzayrwjvks\n" +
                "\n" +
                "krybec\n" +
                "ryk\n" +
                "yrk\n" +
                "kyr\n" +
                "yrk\n" +
                "\n" +
                "xkhdreqfbyipmzalco\n" +
                "wiepqtyhxflvcomabjdsz\n" +
                "\n" +
                "jpgankzcvbtw\n" +
                "kxzugtvnbjp\n" +
                "gknqpjxzvtb\n" +
                "kbtjpvzgmn\n" +
                "bptzvmjkng\n" +
                "\n" +
                "hdaxwiypslz\n" +
                "ndbylw\n" +
                "xdkwtflpyqsz\n" +
                "wlrvcdyjg\n" +
                "mlfewsqodyu\n" +
                "\n" +
                "c\n" +
                "c\n" +
                "o\n" +
                "c\n" +
                "\n" +
                "mah\n" +
                "a\n" +
                "gwa\n" +
                "\n" +
                "heczudoqwmvtyab\n" +
                "acevwozyqtdumhb\n" +
                "\n" +
                "v\n" +
                "e\n" +
                "\n" +
                "rom\n" +
                "mor\n" +
                "romi\n" +
                "rom\n" +
                "\n" +
                "uxdj\n" +
                "d\n" +
                "\n" +
                "p\n" +
                "p\n" +
                "m\n" +
                "db\n" +
                "t\n" +
                "\n" +
                "dtpzeykh\n" +
                "pkdhryzetu\n" +
                "zdkhtpyac\n" +
                "\n" +
                "qanetkhrc\n" +
                "ndlhkceqof\n" +
                "\n" +
                "khbfjlnacvz\n" +
                "cmavfjlkn\n" +
                "aynljofvqkgc\n" +
                "tlkjcnavfm\n" +
                "\n" +
                "ejcbnl\n" +
                "mbgcoiuhsfl\n" +
                "qblyc\n" +
                "blyjevc\n" +
                "\n" +
                "vgqlcfhnx\n" +
                "xwgonuc\n" +
                "pystigbca\n" +
                "cnqlgmdk\n" +
                "rlfcwg\n" +
                "\n" +
                "nazyhitgcjr\n" +
                "nytgizahwprjc\n" +
                "zjcgrinmahyt\n" +
                "nrcdhzgjyati\n" +
                "\n" +
                "xtljebqpg\n" +
                "bpjewtgn\n" +
                "gjtpebx\n" +
                "gmoipkebtcsj\n" +
                "ptwejlbng\n" +
                "\n" +
                "e\n" +
                "exa\n" +
                "\n" +
                "h\n" +
                "nohegc\n" +
                "h\n" +
                "\n" +
                "ivbgpd\n" +
                "isfglyvbdo\n" +
                "dgvbi\n" +
                "bdivug\n" +
                "gvikbd\n" +
                "\n" +
                "wyjmpxghiqfeoctdnbuar\n" +
                "qetnaimxlgsfcbrpj\n" +
                "kbcrhxgjnqpadefzimwt\n" +
                "\n" +
                "kindbwqlusyh\n" +
                "tpzryjgehaucfmov\n" +
                "\n" +
                "wzgou\n" +
                "ugo\n" +
                "guo\n" +
                "voug\n" +
                "\n" +
                "ndwhzsrugpjmltxiqofvkbyc\n" +
                "lgirqyotwjbmvuspfnxhdzck\n" +
                "jbqzgwcvhxofkrmsdlytpuni\n" +
                "xrqzfjolsywtcghdbmukpivn\n" +
                "oqryngdmhljvctxwkbfusipz\n" +
                "\n" +
                "saw\n" +
                "as\n" +
                "sa\n" +
                "msajv\n" +
                "sfa\n" +
                "\n" +
                "oxtrnhvfqyswldb\n" +
                "tmzwgrakc\n" +
                "\n" +
                "coqyrbzjhsmwivanep\n" +
                "xkshzgft\n" +
                "hsz\n" +
                "slzh\n" +
                "\n" +
                "z\n" +
                "glh\n" +
                "\n" +
                "dtusogw\n" +
                "fmpkzvbxnjwh\n" +
                "eaqdciyw\n" +
                "\n" +
                "bgcyqhrztvdxwn\n" +
                "vqtanbyurxczowdg\n" +
                "kmjxyvnbqztfgcrwd\n" +
                "\n" +
                "vospejybinm\n" +
                "fiosvkbnjep\n" +
                "johqpznbeisv\n" +
                "iysbokmjvepn\n" +
                "\n" +
                "nxsrfohagwb\n" +
                "agblosrxwnhf\n" +
                "xgircuhsaobfw\n" +
                "hfxpgosarnbw\n" +
                "\n" +
                "bgqurk\n" +
                "eumkrnvxqg\n" +
                "gkrqhspafuoc\n" +
                "qtogubkr\n" +
                "\n" +
                "bxlapnm\n" +
                "nptix\n" +
                "oqxpn\n" +
                "npx\n" +
                "\n" +
                "rytbpswaezlufdqxo\n" +
                "imazhtjqnglc\n" +
                "\n" +
                "encpqudzigamorv\n" +
                "vamkeznqirdcgp\n" +
                "opvrglqsmcindzae\n" +
                "mpvncrisdezaqg\n" +
                "\n" +
                "ikxqemun\n" +
                "zadbkqjtxney\n" +
                "kenmpxuoq\n" +
                "\n" +
                "vjdqxfyhckrpton\n" +
                "hmngcfpytkdxqvo\n" +
                "ohdvuywpstzkcaqf\n" +
                "\n" +
                "tepj\n" +
                "te\n" +
                "ecvty\n" +
                "\n" +
                "jqotiphkmsexvfugd\n" +
                "gwpyfuhlevkdiotjqx\n" +
                "tjkfvghibocaqxeudp\n" +
                "onexjzpgthuidfkvqs\n" +
                "\n" +
                "ltfq\n" +
                "lqts\n" +
                "oqtl\n" +
                "\n" +
                "nqsyglepwzhmtiojbuvxf\n" +
                "wihkgaoydpzvfxclsenqjmt\n" +
                "\n" +
                "fqxmt\n" +
                "bsgtmxqyrjfdv\n" +
                "tfqmx\n" +
                "itmhqwfx\n" +
                "qtmxf\n" +
                "\n" +
                "rgv\n" +
                "vjwo\n" +
                "nlekpa\n" +
                "\n" +
                "ldytkguwhazeqpb\n" +
                "pqzaytglhbmfuedki\n" +
                "dqbatkpyezhglu\n" +
                "ztgyqjebhkdvpual\n" +
                "kpalzeytqghudb\n" +
                "\n" +
                "xsynhr\n" +
                "hsnury\n" +
                "\n" +
                "qyjukdtmnwhrczvolsb\n" +
                "ymsutqrchdblznowvj\n" +
                "\n" +
                "mpw\n" +
                "wmq\n" +
                "tdwm\n" +
                "wmd\n" +
                "\n" +
                "n\n" +
                "n\n" +
                "n\n" +
                "no\n" +
                "\n" +
                "vnutqbxrygmjwhks\n" +
                "rhoalixstfyuq\n" +
                "\n" +
                "jeyfhsotc\n" +
                "setchyoj\n" +
                "hcyoejst\n" +
                "\n" +
                "ylhpvfiawoekjbq\n" +
                "pkroabqvljiyefhw\n" +
                "\n" +
                "akqbyjpziglmfedw\n" +
                "wjdbyeaqpzligmkf\n" +
                "lfikyqwzbmadjegp\n" +
                "aswgkzdyfrqpmnlibje\n" +
                "fqpmyedjklgzibaw\n" +
                "\n" +
                "qe\n" +
                "eqo\n" +
                "\n" +
                "jbxoe\n" +
                "qoikde\n" +
                "\n" +
                "c\n" +
                "n\n" +
                "j\n" +
                "j\n" +
                "j\n" +
                "\n" +
                "rfh\n" +
                "rhf\n" +
                "rfyh\n" +
                "rhbf\n" +
                "qfrh\n" +
                "\n" +
                "hokvgpxyunam\n" +
                "bmpyogvhunlw\n" +
                "morevjuznhydgit\n" +
                "\n" +
                "ohns\n" +
                "nhos\n" +
                "ohns\n" +
                "hons\n" +
                "hsno\n" +
                "\n" +
                "kxclzyqpan\n" +
                "aexnyqzkpc\n" +
                "pakcqnxzy\n" +
                "\n" +
                "gkytw\n" +
                "mgtw\n" +
                "gptmw\n" +
                "\n" +
                "fixsozjwykhupqmvtbrc\n" +
                "syimxhzbpwcktrofuvjq\n" +
                "xuiwfjvzcpykqhbrosmt\n" +
                "mwrbvqjtkcsipxfolyhzu\n" +
                "\n" +
                "bzhxpyfmk\n" +
                "yfzxmakphb\n" +
                "mkzpxbhyof\n" +
                "hbmzfkxpwyu\n" +
                "pxzhkoybmf\n" +
                "\n" +
                "osdyp\n" +
                "dbsroy\n" +
                "sydoj\n" +
                "\n" +
                "yterzphvxdm\n" +
                "vtxrmyhzedp\n" +
                "vymperdhxtz\n" +
                "mpxrvyhedzt\n" +
                "\n" +
                "esakn\n" +
                "cseak\n" +
                "hxasge\n" +
                "enksta\n" +
                "\n" +
                "u\n" +
                "gfzua\n" +
                "\n" +
                "jsymd\n" +
                "dmxjy\n" +
                "jmdy\n" +
                "xymjd\n" +
                "\n" +
                "sezfhlvxmaqtd\n" +
                "ajvtmqsecyghfixzwl\n" +
                "ksbhxzvafqpmuet\n" +
                "zfeqytxhadmsvc\n" +
                "nextsvazhmyfq\n" +
                "\n" +
                "rucla\n" +
                "auclyr\n" +
                "uticrapl\n" +
                "\n" +
                "akizsuwdmnhpxbgyceft\n" +
                "gwxpfeoyihcklbndasz\n" +
                "zwhsbigdynkpxceaf\n" +
                "\n" +
                "zag\n" +
                "vmisa\n" +
                "yphkcant\n" +
                "jdma\n" +
                "bia\n" +
                "\n" +
                "nplydbkoq\n" +
                "oasptkqgldnbey\n" +
                "doypnqklbc\n" +
                "yblkodncpuq\n" +
                "lqkynpdob\n" +
                "\n" +
                "hmj\n" +
                "jm\n" +
                "\n" +
                "gniearxpdbjlkfm\n" +
                "qdvjlute\n" +
                "\n" +
                "omsihqlnwzbt\n" +
                "blzmhisnqoftw\n" +
                "onqlmwsetzbphi\n" +
                "\n" +
                "jzoxcwdf\n" +
                "wdcjzifxq\n" +
                "\n" +
                "ykdshgzwjfecimnp\n" +
                "jhipmsaftezkoc\n" +
                "ziaspcjfmkhve\n" +
                "\n" +
                "t\n" +
                "t\n" +
                "t\n" +
                "f\n" +
                "\n" +
                "zmevcjhbsainxoquwpftkydlr\n" +
                "cygwbtvxemnzfjhrqkdspaolu\n" +
                "efdtnrlwczymxqvpsoukjbah\n" +
                "\n" +
                "oujkhnlzydsirva\n" +
                "dxgzjsuptaohqvnkic\n" +
                "aoiujdlnkzehvs\n" +
                "uriadhksjyoznv\n" +
                "iydmovnzakhfusj\n" +
                "\n" +
                "ycajzrtie\n" +
                "zctyriesap\n" +
                "pxiacrztehby\n" +
                "qaenyxtzirc\n" +
                "saecrytzi\n" +
                "\n" +
                "xrnjkgdpuzqvcm\n" +
                "ndqkvuxczjpgrm\n" +
                "ucgmzjpqrnxkvd\n" +
                "npqxkumdcezvgrj\n" +
                "\n" +
                "thymlxwaoz\n" +
                "ylhowtmazx\n" +
                "\n" +
                "nwaisrejbtqfmh\n" +
                "mbwhqnrfjesa\n" +
                "hfnrqebjasmw\n" +
                "jecwhfgrsqodanmb\n" +
                "qasbhnjwferm\n" +
                "\n" +
                "ny\n" +
                "ny\n" +
                "yne\n" +
                "\n" +
                "lgkmfbthwaouscxpznvyrdi\n" +
                "nhlmtpwyrojfvbuaczxkgds\n" +
                "askbuvdozmnxhfygrlwctp\n" +
                "fytznqhlbmxgrwcdoupavks\n" +
                "wcplxyvsrdjnfgkmuzbtaho\n" +
                "\n" +
                "fklceui\n" +
                "kclfiue\n" +
                "klefiuc\n" +
                "clfekiu\n" +
                "iklcufe\n" +
                "\n" +
                "yavcmhwbp\n" +
                "capvymhbw\n" +
                "whypmabcv\n" +
                "pbzmcywvhja\n" +
                "\n" +
                "lbevjz\n" +
                "gnvefbu\n" +
                "webvd\n" +
                "\n" +
                "ewzcqndmjhvy\n" +
                "jevrqnym\n" +
                "guqpiotaevsbmynlj\n" +
                "vqmekjynf\n" +
                "nefqmjxvy\n" +
                "\n" +
                "akgwyjfi\n" +
                "giwfyljak\n" +
                "\n" +
                "pdejr\n" +
                "jerd\n" +
                "redj\n" +
                "\n" +
                "liwtk\n" +
                "kiwl\n" +
                "wikl\n" +
                "\n" +
                "rbwvox\n" +
                "bxvnor\n" +
                "vbwxro\n" +
                "vkrxob\n" +
                "xbvirwo\n" +
                "\n" +
                "ntsbkwqefjphro\n" +
                "nqdvgxihopwc\n" +
                "\n" +
                "dn\n" +
                "nd\n" +
                "nd\n" +
                "\n" +
                "j\n" +
                "f\n" +
                "g\n" +
                "k\n" +
                "j\n" +
                "\n" +
                "tfsul\n" +
                "usftl\n" +
                "\n" +
                "ov\n" +
                "v\n" +
                "w\n" +
                "tj\n" +
                "sl\n" +
                "\n" +
                "gdlufaesv\n" +
                "uagvd\n" +
                "vudag\n" +
                "\n" +
                "cbegxmuiwkzo\n" +
                "okrmgbfwvnecp\n" +
                "uybxehawmgqkoc\n" +
                "yloqmbwgtczke\n" +
                "\n" +
                "jms\n" +
                "ymsfjo\n" +
                "lmsuiwhe\n" +
                "ydsmk\n" +
                "\n" +
                "wgckujsd\n" +
                "irp\n" +
                "\n" +
                "zgeulsjvimptdaxrqnk\n" +
                "zbxtefdmvganulqprikjs\n" +
                "ptslznrjqkxemagiudv\n" +
                "\n" +
                "fqtb\n" +
                "qp\n" +
                "aq\n" +
                "q\n" +
                "q\n" +
                "\n" +
                "hrkzci\n" +
                "bhwkpidxtflcue\n" +
                "hkic\n" +
                "chki\n" +
                "kcjhiv\n" +
                "\n" +
                "gi\n" +
                "s\n" +
                "\n" +
                "rakewmostbfvjzgi\n" +
                "begtioavfrkzjm\n" +
                "zoeikjtbfagrvm\n" +
                "\n" +
                "xnbhdlctm\n" +
                "bgfhwlxsaqnkov\n" +
                "pelmnhuxryb\n" +
                "\n" +
                "e\n" +
                "qr\n" +
                "jh\n" +
                "\n" +
                "vhtwuokdqpa\n" +
                "jfaniksczbeymr\n" +
                "\n" +
                "ngedtljsvybxkmhfuzw\n" +
                "tbzedwsjgknvhlmfu\n" +
                "lzbgdsuhkjtvermwfn\n" +
                "smizqluwdetfavbnhjg\n" +
                "blwtngusvdjzhefm\n" +
                "\n" +
                "lxaiqvkoh\n" +
                "feioxvwbsrl\n" +
                "\n" +
                "fy\n" +
                "yfbqlm\n" +
                "fy\n" +
                "yf\n" +
                "yf\n" +
                "\n" +
                "cuygpzd\n" +
                "kv\n" +
                "k\n" +
                "v\n" +
                "\n" +
                "antp\n" +
                "nat\n" +
                "\n" +
                "uk\n" +
                "ku\n" +
                "uk\n" +
                "\n" +
                "tdjbri\n" +
                "rdwezgjtlck\n" +
                "stvfhapyx\n" +
                "\n" +
                "psu\n" +
                "spy\n" +
                "ps\n" +
                "pksy\n" +
                "bpsq\n" +
                "\n" +
                "db\n" +
                "o\n" +
                "o\n" +
                "\n" +
                "yi\n" +
                "iq\n" +
                "pmxi\n" +
                "i\n" +
                "\n" +
                "oxt\n" +
                "atox\n" +
                "txo\n" +
                "\n" +
                "wn\n" +
                "sgzth\n" +
                "b\n" +
                "m\n" +
                "ynq\n" +
                "\n" +
                "ayxvhzu\n" +
                "vhyzxu\n" +
                "hvzuyx\n" +
                "\n" +
                "cxoygklt\n" +
                "toky\n" +
                "ovkpyt\n" +
                "voystpk\n" +
                "\n" +
                "yqtjwifbvsn\n" +
                "vstyfbxjqwin\n" +
                "vsjtinqfwby\n" +
                "qxysnitjwfvb\n" +
                "bjfynsthqiwv\n" +
                "\n" +
                "zobny\n" +
                "zynob\n" +
                "ozbyn\n" +
                "noybz\n" +
                "onyzb\n" +
                "\n" +
                "inpdmtkblgqrvaowzxu\n" +
                "zhrbpuwiqdomgvlnt\n" +
                "topveguwzrcbndmqli\n" +
                "\n" +
                "eapmtqrski\n" +
                "islukrmpe\n" +
                "sevcbzfngx\n" +
                "\n" +
                "pcbl\n" +
                "vxqwe\n" +
                "\n" +
                "ky\n" +
                "t\n" +
                "p\n" +
                "qzfo\n" +
                "\n" +
                "bkhdlpnrxezivu\n" +
                "lztsfxpgknho\n" +
                "knwlxmzjhpy\n" +
                "\n" +
                "t\n" +
                "ita\n" +
                "oqt\n" +
                "sbt\n" +
                "\n" +
                "omwk\n" +
                "eowm\n" +
                "wmo\n" +
                "wmo\n" +
                "osbtmxwd\n" +
                "\n" +
                "dwgpvjemitbcnuhr\n" +
                "vyjlitenkbpmuhqwxd\n" +
                "iedvbwjczstunpmhg\n" +
                "\n" +
                "yfakujntsriwgxm\n" +
                "rfatigyjkxusnm\n" +
                "uyxitmkagnjfs\n" +
                "isjafytxumgnek\n" +
                "tiknjmugxsyaf\n" +
                "\n" +
                "pahkyfojrv\n" +
                "enxmd\n" +
                "\n" +
                "sehnkcr\n" +
                "shkrc\n" +
                "hcwxilkru\n" +
                "skgchrfpjt\n" +
                "\n" +
                "zdcvpant\n" +
                "nizclpmtgbv\n" +
                "jtcpnzv\n" +
                "phtnscvza\n" +
                "azcntrowvpd\n" +
                "\n" +
                "ativhgmyedozw\n" +
                "nvztmiahewg\n" +
                "uhaimgzventw\n" +
                "txiqfmzglphvwae\n" +
                "ehmgiwtzav\n" +
                "\n" +
                "qdpreikohtyjc\n" +
                "ihtydekrocpqj\n" +
                "djkoticqhpery\n" +
                "jcorkdepqyiht\n" +
                "\n" +
                "kgwunqm\n" +
                "qgjunwk\n" +
                "oinqruwzyk\n" +
                "\n" +
                "wtkqceimludr\n" +
                "mkhpwdcqleurzt\n" +
                "mqweldutkcr\n" +
                "kdtmwceulrq\n" +
                "rqlutcidwmke\n" +
                "\n" +
                "k\n" +
                "h\n" +
                "k\n" +
                "k\n" +
                "k\n" +
                "\n" +
                "irb\n" +
                "arbi\n" +
                "bri\n" +
                "irb\n" +
                "fbxvri\n" +
                "\n" +
                "umpkng\n" +
                "qmnugpk\n" +
                "\n" +
                "sbdxmlzacj\n" +
                "sbzlcamjxd\n" +
                "cajmslzxdb\n" +
                "\n" +
                "fwndcxr\n" +
                "xbmusn\n" +
                "\n" +
                "t\n" +
                "t\n" +
                "gh\n" +
                "p\n" +
                "t\n" +
                "\n" +
                "zovqiwdhuaslkjxrbcnt\n" +
                "flhnkoxvadiqrwpzbjs\n" +
                "gqkisrxodznabjwvlhp\n" +
                "koqlswdahnzjvbrmyxie\n" +
                "\n" +
                "apecofvgshiyqbj\n" +
                "icegjhasytobfpvq\n" +
                "ocsheqagjfpyivb\n" +
                "pewjncobqiysgzrfahv\n" +
                "\n" +
                "wzomnlgyxj\n" +
                "thazprgi\n" +
                "\n" +
                "rywgaemsubhvkqcozpnxl\n" +
                "avehbwolxnzmqyprgu\n" +
                "qyrgpxhazluvenobmw\n" +
                "jhtrzywlnmbeoxvgpiaqu\n" +
                "gavmwzrponyxhduqble\n" +
                "\n" +
                "tw\n" +
                "wt\n" +
                "tw\n" +
                "\n" +
                "qpzxrctf\n" +
                "\n" +
                "iqpunlsawtcykmxbdvgfzjr\n" +
                "vnwdruyptakbgqxjimlzcfs\n" +
                "fgizdmcblparnsvtuqwxkjy\n" +
                "pxwylavndgqtjbicfksmzru\n" +
                "xtpdfrbkcglzvqjuminaysw\n" +
                "\n" +
                "xkyvhtdwpjnulig\n" +
                "hvegnyitdwxjz\n" +
                "vthsnxjaywdig\n" +
                "whdagyqvxjtni\n" +
                "wjvgytdaxnhi\n" +
                "\n" +
                "ygduev\n" +
                "clqoa\n" +
                "qxc\n" +
                "xaz\n" +
                "fc\n" +
                "\n" +
                "rzeqvofasyhjgxwkmtcudn\n" +
                "vkuogexmwhznrycdqft\n" +
                "zupwcondeklthrbvxgmyfqi\n" +
                "\n" +
                "mtredzn\n" +
                "xcnozebtrmd\n" +
                "elzrmwtund\n" +
                "emtdnrz\n" +
                "tedmzorn\n" +
                "\n" +
                "tlbunpqygz\n" +
                "xmehasrifvwj\n" +
                "\n" +
                "hoskgitlw\n" +
                "owrailhtfkg\n" +
                "wigbjvhtolk\n" +
                "tbhivwgsuklo\n" +
                "\n" +
                "fxnachtsdmiwvuzkg\n" +
                "hacwldskfgvuixmtzn\n" +
                "xghufdizawvnmsctk\n" +
                "\n" +
                "gnauvfizjdortq\n" +
                "rinjautyqdzvg\n" +
                "giunqazvtdrjmc\n" +
                "wndhjzuqviatgr\n" +
                "\n" +
                "vtpsy\n" +
                "sptvy\n" +
                "svpty\n" +
                "ptksyv\n" +
                "\n" +
                "yaskce\n" +
                "xdtvyjnqma\n" +
                "faoyb\n" +
                "psyfa\n" +
                "\n" +
                "lbxounj\n" +
                "lijrmoxnb\n" +
                "mioybjnx\n" +
                "afbjnvopxsch\n" +
                "bjlzoknx\n" +
                "\n" +
                "vqmsgwjfkzdbthal\n" +
                "jszvlwthkmqfgdba\n" +
                "akmfjzgldswvqth\n" +
                "tuswfahjmdqkgvlcz\n" +
                "jvatqgfmnwzhdksl\n" +
                "\n" +
                "uqyfkzdwta\n" +
                "hctzeiywabpgvlqonmuf\n" +
                "zyurtaqwsxf\n" +
                "wyruzjaqft\n" +
                "\n" +
                "rwltyhqdecxagbov\n" +
                "azthexlkoqmvrdngcwfs\n" +
                "corjvwqhutexadlg\n" +
                "lecogwrhavqdtx\n" +
                "qpdvrgctyaohwlex\n" +
                "\n" +
                "egsilhd\n" +
                "hxmijg\n" +
                "\n" +
                "tzdmnvsyiwjrhakbgp\n" +
                "wmzhsctpdrbnagvyei\n" +
                "bvwtaylgdnzhsmipr\n" +
                "rhmlswzvpandgtybi\n" +
                "\n" +
                "qriopbacexhnlwfvsmdk\n" +
                "wblaondrszhcfpei\n" +
                "pdnahlrjseiwfcob\n" +
                "cerwaoshjldbfnipzu\n" +
                "oalsrdienwcfhpb\n" +
                "\n" +
                "xcpe\n" +
                "pcx\n" +
                "cxpl\n" +
                "nbpyzixc\n" +
                "lpecx\n" +
                "\n" +
                "xyfcgdaew\n" +
                "jdlcopnaixqbv\n" +
                "ehkcdrax\n" +
                "dcytarmuhgxews\n" +
                "\n" +
                "bqozpsd\n" +
                "pqzosd\n" +
                "zgqdop\n" +
                "ocqzdfp\n" +
                "\n" +
                "uxy\n" +
                "szj\n" +
                "jzl\n" +
                "fhvk\n" +
                "\n" +
                "muz\n" +
                "m\n" +
                "omycvi\n" +
                "im\n" +
                "\n" +
                "t\n" +
                "u\n" +
                "\n" +
                "xslkmbzarnfeo\n" +
                "axmndjpsqzelrbkfo\n" +
                "eykroszbaxlmhfn\n" +
                "\n" +
                "rsz\n" +
                "rzq\n" +
                "kzrit\n" +
                "\n" +
                "hkmqiydpzlosuanvwj\n" +
                "czsjklbvwaidhnxpu\n" +
                "ejvwqmatlkziundhps\n" +
                "udgjnfoepkwilrhsvaz\n" +
                "\n" +
                "czlnqtdy\n" +
                "bcv\n" +
                "cvga\n" +
                "hvcb\n" +
                "ac\n" +
                "\n" +
                "lcmytwdeqifzakjhuon\n" +
                "mdqxhfgpzykvteajn\n" +
                "emfpxqnhbykzdatj\n" +
                "\n" +
                "rtgmujlen\n" +
                "eguclrkmtnj\n" +
                "npjgemtrlu\n" +
                "untmegrjl\n" +
                "\n" +
                "olykiz\n" +
                "orxyswdtka\n" +
                "\n" +
                "qelnh\n" +
                "yijmfxtvbs\n" +
                "gweh\n" +
                "wrc\n" +
                "\n" +
                "vjcediawtnrmoh\n" +
                "lvnhmabrxcjwet\n" +
                "ajmkbntrvchlegw\n" +
                "\n" +
                "yicrxeztbdpjuqlfgnvksmah\n" +
                "rayjtgdsfhexiqvpcznlkubm\n" +
                "crxijflabsgkhtqmdeunpvyz\n" +
                "\n" +
                "gpbklvxy\n" +
                "pybxg\n" +
                "ypwgxbd\n" +
                "gpxyb\n" +
                "\n" +
                "vos\n" +
                "sv\n" +
                "vs\n" +
                "\n" +
                "hqiktnmezpvacby\n" +
                "uekhv\n" +
                "egskvh\n" +
                "kvehog\n" +
                "\n" +
                "myhoetiwlqrpdk\n" +
                "pgfkbqleywmhtic\n" +
                "tezpslhymwkiq\n" +
                "\n" +
                "t\n" +
                "vxh\n" +
                "g\n" +
                "t\n" +
                "\n" +
                "gjimn\n" +
                "ijugmn\n" +
                "njmgi\n" +
                "\n" +
                "drojlynvs\n" +
                "nrysdjvlo\n" +
                "lydosnjvr\n" +
                "sjylnrodv\n" +
                "nyjrdvols\n" +
                "\n" +
                "vjrclek\n" +
                "vuljbckqfteds\n" +
                "cihklevgj\n" +
                "\n" +
                "rqbvni\n" +
                "flxuv\n" +
                "\n" +
                "gpywjntefcm\n" +
                "cnoaetmyjpgd\n" +
                "mpeynjcg\n" +
                "rbnpymcgexzhqji\n" +
                "cjumnegpwy\n" +
                "\n" +
                "h\n" +
                "c\n" +
                "h\n" +
                "h\n" +
                "h\n" +
                "\n" +
                "hzrqoybi\n" +
                "wynqkcmlduae\n" +
                "zqybh\n" +
                "\n" +
                "itnoq\n" +
                "rtinoq\n" +
                "tqhlin\n" +
                "imtbq\n" +
                "\n" +
                "moetialxhyqkznjwscgdpv\n" +
                "qwcagyzjvtoednmixlsphk\n" +
                "kxqajsiotvnlhcgwdzympe\n" +
                "ynejvlhsopakcmzdtxgiqw\n" +
                "yaxdpiqktjsozmgvncewlh\n" +
                "\n" +
                "qyrlgevbzsutwmxjhindcaokp\n" +
                "vtdjrqaocngwehspylbukmz\n" +
                "\n" +
                "aev\n" +
                "ve\n" +
                "a\n" +
                "byqg\n" +
                "\n" +
                "ycfvpamkhliot\n" +
                "wmckyrthxusfqiedjlaz\n" +
                "atcmhkboiylf\n" +
                "\n" +
                "sfqkmlhdc\n" +
                "mlhkscqdf\n" +
                "fcqsdhmlk\n" +
                "kqfhcdmsl\n" +
                "kqslzfdmhoc\n" +
                "\n" +
                "dgveoupsmhabyfkrztclj\n" +
                "vedwkmptusfhzaygqolcr\n" +
                "\n" +
                "tfoaevgbi\n" +
                "yfu\n" +
                "sfwqh\n" +
                "kpfxlj\n" +
                "dufl\n" +
                "\n" +
                "mlwhb\n" +
                "jvgtzp\n" +
                "\n" +
                "jzp\n" +
                "szwipyj\n" +
                "\n" +
                "larkxcqsbpeuiv\n" +
                "fharycntpzi\n" +
                "\n" +
                "lsympnqboj\n" +
                "nlpjmobqys\n" +
                "njoslbqpym\n" +
                "qsnodjtlmbyp\n" +
                "lnosbmpjyq\n" +
                "\n" +
                "jpovmflgikracyqunwthe\n" +
                "hawgrlcyvpnmkjeofuit\n" +
                "pltojwgrcfkhaneuivmy\n" +
                "klaoumwtfgejnhcripvy\n" +
                "\n" +
                "hmvxakwrtundglz\n" +
                "mkacvnhwrlxbzdug\n" +
                "\n" +
                "asvoizlprxjefycmthugnqw\n" +
                "zohmwpxdaiyvrfnulecgjtq\n" +
                "\n" +
                "natmhjdg\n" +
                "zctmdalg\n" +
                "vbiamufq\n" +
                "\n" +
                "vhxbajdokyn\n" +
                "dkvxonyhmab\n" +
                "hnexvbdaoyk\n" +
                "\n" +
                "gyjfnm\n" +
                "gmfnyj\n" +
                "jfygmn\n" +
                "\n" +
                "bjqn\n" +
                "bnqj\n" +
                "nqbj\n" +
                "qbnj\n" +
                "\n" +
                "hawjpsxeolr\n" +
                "rwlqenjhpsobgamx\n" +
                "\n" +
                "tovhgbwjdckpqn\n" +
                "ifzl\n" +
                "mleysuzrax\n" +
                "\n" +
                "sky\n" +
                "ky\n" +
                "mgfpwk\n" +
                "\n" +
                "zx\n" +
                "h\n" +
                "ict\n" +
                "gz\n" +
                "\n" +
                "zsjitm\n" +
                "lijor\n" +
                "jmwabyit\n" +
                "\n" +
                "nbzmj\n" +
                "abvfwrdn\n" +
                "csnbm\n" +
                "\n" +
                "hdqyski\n" +
                "ywvclhdsq\n" +
                "hsqbyxd\n" +
                "\n" +
                "jmt\n" +
                "mtsuhxjzkla\n" +
                "\n" +
                "fijlt\n" +
                "psjbtfieg\n" +
                "zqcohan\n" +
                "\n" +
                "gwnfpqb\n" +
                "pnwf\n" +
                "wpnf\n" +
                "wfnp\n" +
                "nwpf\n" +
                "\n" +
                "irgkabh\n" +
                "khgibar\n" +
                "akgirhb\n" +
                "\n" +
                "emonkbuycsz\n" +
                "noyzscmuk\n" +
                "\n" +
                "ejsqzftblax\n" +
                "scomdrxgibw\n" +
                "\n" +
                "afdjtiyvgqorsmnhubweplkxzc\n" +
                "fmznscjliqbyevhxwoktdugrap\n" +
                "\n" +
                "cgyxhiubmptdokesrjzlafq\n" +
                "pmdqvjuygbeslzatokxfr\n" +
                "\n" +
                "hyawt\n" +
                "wh\n" +
                "wh\n" +
                "wh\n" +
                "\n" +
                "vojux\n" +
                "ei\n" +
                "nq\n" +
                "\n" +
                "pvnjgmxksluctq\n" +
                "zfrdoa\n" +
                "\n" +
                "d\n" +
                "z\n" +
                "x\n" +
                "xd\n" +
                "d\n" +
                "\n" +
                "dwpscgknx\n" +
                "kwxc\n" +
                "xcwk\n" +
                "wxkci\n" +
                "\n" +
                "qipb\n" +
                "ildp\n" +
                "ziacpr\n" +
                "pbdi\n" +
                "\n" +
                "x\n" +
                "xb\n" +
                "x\n" +
                "x\n" +
                "x\n" +
                "\n" +
                "fenqcuwi\n" +
                "niczkhxeq\n" +
                "mcejqnxit\n" +
                "iycrngpqel\n" +
                "\n" +
                "uyj\n" +
                "yju\n" +
                "yuj\n" +
                "ujy\n" +
                "\n" +
                "b\n" +
                "bd\n" +
                "\n" +
                "e\n" +
                "e\n" +
                "e\n" +
                "e\n" +
                "fei\n" +
                "\n" +
                "tncbizahupsdwlog\n" +
                "oclbqdskwnaymx\n" +
                "atloswndebjcriv\n" +
                "\n" +
                "msojaeqnphzylgdbc\n" +
                "ebmzlphcgyjoadq\n" +
                "\n" +
                "apehlz\n" +
                "tozlmeba\n" +
                "ekyflaz\n" +
                "\n" +
                "qpnhfgjdzymlctkrb\n" +
                "slmbhkqpfyngzj\n" +
                "mlpqjyzbghnkf\n" +
                "nmzghjyblkfpq\n" +
                "bngqfhymkzpjl\n" +
                "\n" +
                "apgvczsfuybdiklq\n" +
                "gmhxdubftesavzlpjcqyi\n" +
                "aswyzugkicpfvqldb\n" +
                "oylsvgbcnuqzdafpi\n" +
                "\n" +
                "ncrkh\n" +
                "nhkrc\n" +
                "kncrh\n" +
                "hkrnc\n" +
                "hcknr\n" +
                "\n" +
                "nvrjtzamfuhqxp\n" +
                "ebdigavktsywflmco\n" +
                "\n" +
                "evrabhcmxkonl\n" +
                "vlcxmbnkrheo\n" +
                "cxloknrmeb\n" +
                "pkclmerbonx\n" +
                "lbkoryunexmc\n" +
                "\n" +
                "zdmhgatfpqcwrsu\n" +
                "beravdksgly\n" +
                "\n" +
                "wfo\n" +
                "fw\n" +
                "bfwh\n" +
                "\n" +
                "kpzlhbtjfiw\n" +
                "fjwpzhkbli\n" +
                "bfhpkjzwil\n" +
                "pjwoikhzlbf\n" +
                "\n" +
                "yworad\n" +
                "adsyr\n" +
                "\n" +
                "atqhenzlswmufgkojrb\n" +
                "lfoanzusbhgtjkyeqwm\n" +
                "nsgajlhqeobkfztwmu\n" +
                "mlcisaozwkhetnqfjgbdu\n" +
                "\n" +
                "xhqkmdutfzasylbw\n" +
                "hqubgdwxlztkmsyfae\n" +
                "pfhuacyitsqxmbwlzkd\n" +
                "\n" +
                "tqbpnosumlj\n" +
                "jdtpqbyoli\n" +
                "ulobptqjn\n" +
                "tfqlvwzopbajc\n" +
                "jxpeobqtulis\n" +
                "\n" +
                "awg\n" +
                "wag\n" +
                "awgk\n" +
                "\n" +
                "czbledy\n" +
                "avgwqu\n" +
                "\n" +
                "kf\n" +
                "f\n" +
                "\n" +
                "bh\n" +
                "gm\n" +
                "tj\n" +
                "\n" +
                "l\n" +
                "dm\n" +
                "lspg\n" +
                "zfeauxn\n" +
                "qt\n" +
                "\n" +
                "zwep\n" +
                "pwze\n" +
                "wpze\n" +
                "ewzp\n" +
                "\n" +
                "jptngbzhk\n" +
                "tgnkrpzxdjh\n" +
                "ghjznktp\n" +
                "\n" +
                "ofrbuieszcakqt\n" +
                "snomauqcerdpbt\n" +
                "\n" +
                "nbjxhyvtpl\n" +
                "tbxzgovhjy\n" +
                "yhbtxjovizk\n" +
                "bytvxhj\n" +
                "\n" +
                "pibogfjn\n" +
                "fogbinjl\n" +
                "bonqgfji\n" +
                "banjisugcmwfvoe\n" +
                "iobghfjn\n" +
                "\n" +
                "tz\n" +
                "t\n" +
                "ta\n" +
                "\n" +
                "qnraf\n" +
                "qrxf\n" +
                "qfr\n" +
                "ezroqf\n" +
                "\n" +
                "iachtzfemxwbs\n" +
                "gzsfycehaqwkm\n" +
                "twmhzcsbrafe\n" +
                "zmafhcewxs\n" +
                "\n" +
                "gqoznmrlxvudwehf\n" +
                "uvzrohmlgdnwqxef\n" +
                "frgvqedxohmlnuwz\n" +
                "fqledmnvwghruzxo\n" +
                "\n" +
                "rxcvnyjbqgm\n" +
                "cjygxmrvbqn\n" +
                "vuybxmkcrnqg\n" +
                "ipgrxvnobcmeyq\n" +
                "yvqnbmrgcx\n" +
                "\n" +
                "ay\n" +
                "ay\n" +
                "ay\n" +
                "ya\n" +
                "ay\n" +
                "\n" +
                "np\n" +
                "xa\n" +
                "ba\n" +
                "\n" +
                "ibrcmtxqvyaed\n" +
                "vycdaeitmbxqr\n" +
                "dvqiytmcxabre\n" +
                "dvbaicqeyxrtm\n" +
                "\n" +
                "hgzd\n" +
                "zdlho\n" +
                "zhd\n" +
                "zdh\n" +
                "zdh\n" +
                "\n" +
                "hcipn\n" +
                "zchnipb\n" +
                "\n" +
                "rwptzv\n" +
                "ymoedzaltsc\n" +
                "\n" +
                "ubdwmjecyqxltipzfn\n" +
                "mvfulhydqewjtzpnci\n" +
                "\n" +
                "najhotpuyrsxdlqbk\n" +
                "wxetrjaobduqpznklsyc\n" +
                "\n" +
                "jwcgbxoipeyfmkvhr\n" +
                "cmblwpoudxteyfvnhkrg\n" +
                "qzseparbjxvykfocghwm\n" +
                "eqvwroycibpxmfghk\n" +
                "\n" +
                "xwedaqgiznj\n" +
                "khubyeatir\n" +
                "avgncxeljzmsoif\n" +
                "\n" +
                "zf\n" +
                "f\n" +
                "f\n" +
                "htbcr\n" +
                "\n" +
                "st\n" +
                "kmr\n" +
                "rm\n" +
                "tvebzs\n" +
                "cig\n" +
                "\n" +
                "gdij\n" +
                "gvi\n" +
                "jhgies\n" +
                "\n" +
                "fduipkhlz\n" +
                "izdplfu\n" +
                "\n" +
                "pdculaojmwsqebvgh\n" +
                "zmhjsdwlefgoucrpvy\n" +
                "\n" +
                "bzwagcde\n" +
                "uhsqpmloni\n" +
                "\n" +
                "mf\n" +
                "f\n" +
                "ltfn\n" +
                "\n" +
                "xlhmpdyieob\n" +
                "mlxpyhideo\n" +
                "mixkldhpoye\n" +
                "\n" +
                "lwthjcvgnmxuypos\n" +
                "vixqojmy\n" +
                "evrxmoyj\n" +
                "ymkajoxv\n" +
                "zfvjdymaxo\n" +
                "\n" +
                "voh\n" +
                "h\n" +
                "\n" +
                "onqdyf\n" +
                "qmnf\n" +
                "wiktfqsajgn\n" +
                "\n" +
                "poaheifqcl\n" +
                "plqcoifaeh\n" +
                "paegritwhnvlofzucjd\n" +
                "ipeohaflc\n" +
                "oielhpafcs\n" +
                "\n" +
                "tzvenpcqxisbjhmgkrw\n" +
                "xvnckipbhszegfwm\n" +
                "pkchgoxbavsmewizn\n" +
                "csvzekmhyngipxbaw\n" +
                "\n" +
                "wgim\n" +
                "ixaw\n" +
                "wixka\n" +
                "iyownrps\n" +
                "iwk\n" +
                "\n" +
                "caofbkuznsiqrtvpjyg\n" +
                "pyroglzcjtfub\n" +
                "pcfjryzgtubmo\n" +
                "\n" +
                "junoecpfwmhtxkayziqvgrl\n" +
                "zqigynpcvufwohjlemtkxar\n" +
                "oeavkrhizljumtgfpxwcqny\n" +
                "tyizfjnoqcbgxarepklvwsudmh\n" +
                "\n" +
                "itvqcxburwo\n" +
                "idtvacoqbex\n" +
                "btvifjxcqyo\n" +
                "ojikvqcltbx\n" +
                "\n" +
                "bromkxwdfq\n" +
                "dkfrbwqamxo\n" +
                "korxywiqfdmb\n" +
                "\n" +
                "smyfvkg\n" +
                "xmkgvsf\n" +
                "kgnsfvem\n" +
                "mkfvgs\n" +
                "\n" +
                "pdxa\n" +
                "mqgx\n" +
                "lxsezkbjic\n" +
                "xy\n" +
                "wfprx\n" +
                "\n" +
                "ynhepftgslro\n" +
                "wytlefgosarn\n" +
                "ysgtndocwlrf\n" +
                "lrgnfoswtya\n" +
                "zlibfutmrkxsvjnqgyo\n" +
                "\n" +
                "kht\n" +
                "tkh\n" +
                "htk\n" +
                "hkt\n" +
                "\n" +
                "pcdxhjnovlusitq\n" +
                "dbtrjizv\n" +
                "\n" +
                "bjhnkitaegvrsx\n" +
                "nxghvbestra\n" +
                "bwetgsarvhxdn\n" +
                "\n" +
                "oleswygxbnfmtzkjuar\n" +
                "xuaezbtcwlgmnrofsjy\n" +
                "\n" +
                "hdrgyowbfktavjuqlzm\n" +
                "gtkvfdulwqjzhymabro\n" +
                "rzojgmltbyhafvwdqku\n" +
                "\n" +
                "uxpwqbyr\n" +
                "xpquwyrb\n" +
                "rwxyqubp\n" +
                "rwbyquxp\n" +
                "qxrbyuwp\n" +
                "\n" +
                "kqlwz\n" +
                "rkve\n" +
                "klnf\n" +
                "ucqk\n" +
                "\n" +
                "irqgpjmdk\n" +
                "ctqmvnkfbgj\n" +
                "\n" +
                "dv\n" +
                "dv\n" +
                "dv\n" +
                "\n" +
                "fariyqplzoetb\n" +
                "zykjphxcg\n" +
                "\n" +
                "pytmwqvx\n" +
                "txvpqmdwy\n" +
                "xtyqvwmp\n" +
                "wvqmxypt\n" +
                "\n" +
                "oekfrmuatwl\n" +
                "axsvpcjkgqdzhiby\n" +
                "\n" +
                "fnyuqsihvmatgwxlr\n" +
                "ufjmioapebxnqydhtk\n" +
                "\n" +
                "tpskxdqc\n" +
                "kxsqcdtp\n" +
                "ytqsdkxcp\n" +
                "cxpqdtks\n" +
                "tcxpsdqk\n" +
                "\n" +
                "soivtnhezljymw\n" +
                "mhcyptneuvob\n" +
                "nfetymhgdavo\n" +
                "vnbhmxetaoy\n" +
                "\n" +
                "sqruavzncixgbpof\n" +
                "vioanzfgreuxqc\n" +
                "acetqngfrxoziuv\n" +
                "gqcfmxvrnzaoliju\n" +
                "\n" +
                "earxh\n" +
                "gmizfq\n" +
                "\n" +
                "tejlcvwgxpdbhsorufmiz\n" +
                "oftmijdscxlvzbuwpehgry\n" +
                "cvnksdzamhgbporwtufiljxe\n" +
                "\n" +
                "wdmgbxyihk\n" +
                "khmxyidwg\n" +
                "hikxwdlpygm\n" +
                "\n" +
                "nzcf\n" +
                "cz\n" +
                "\n" +
                "vhfecblgmowtqxpaskyi\n" +
                "xwgztblrjiacpfmheksvy\n" +
                "\n" +
                "pemi\n" +
                "e\n" +
                "e\n" +
                "ze\n" +
                "e\n" +
                "\n" +
                "fxwy\n" +
                "xyfw\n" +
                "yzxfw\n" +
                "\n" +
                "kshfqrlmyea\n" +
                "xsqboukan\n" +
                "\n" +
                "vknp\n" +
                "levn\n" +
                "pknv\n" +
                "\n" +
                "vqsdyhzwei\n" +
                "poijeyhscazl\n" +
                "\n" +
                "ryf\n" +
                "ofit\n" +
                "txw\n" +
                "jqvlhmbgeuznps\n" +
                "\n" +
                "qhzycdugf\n" +
                "cuhqdzfg\n" +
                "fghuqzcd\n" +
                "\n" +
                "emqngdv\n" +
                "meaqh\n" +
                "ezqmax\n" +
                "exqm\n" +
                "qmaze\n" +
                "\n" +
                "jgrnahfyvotupkxziqsdmceblw\n" +
                "ntughqlksexifdraozvmbcpwy\n" +
                "\n" +
                "imt\n" +
                "tim\n" +
                "\n" +
                "pthzw\n" +
                "tpnwhz\n" +
                "piztlw\n" +
                "tzpw\n" +
                "\n" +
                "xpuh\n" +
                "xbqrvys\n" +
                "lxw\n" +
                "\n" +
                "cpidsmqk\n" +
                "rkpcdmisq\n" +
                "pcdkqsmi\n" +
                "pmskqdic\n" +
                "\n" +
                "thxqby\n" +
                "bqxohty\n" +
                "qybhxt\n" +
                "yqtbxh\n" +
                "yqbxth\n" +
                "\n" +
                "qkplixrshe\n" +
                "jndbsraivm\n" +
                "zrgelsyit\n" +
                "lfsri\n" +
                "\n" +
                "zqr\n" +
                "zrtc\n" +
                "rz\n" +
                "\n" +
                "deabt\n" +
                "ueatgs\n" +
                "hwiqknj\n" +
                "ulxb\n" +
                "tdm\n" +
                "\n" +
                "sfpwq\n" +
                "phsqw\n" +
                "kpsqw\n" +
                "\n" +
                "guhmbl\n" +
                "gmuhb\n" +
                "mhndpub\n" +
                "yuihmgcb\n" +
                "uismhby\n" +
                "\n" +
                "qioblnp\n" +
                "olnqbip\n" +
                "loqbinp\n" +
                "\n" +
                "rqc\n" +
                "qcr\n" +
                "crqay\n" +
                "rqc\n" +
                "\n" +
                "z\n" +
                "z\n" +
                "z\n" +
                "z\n" +
                "zp\n" +
                "\n" +
                "ljo\n" +
                "lcbajeorg\n" +
                "jlox\n" +
                "oljx\n" +
                "\n" +
                "loasmqxdy\n" +
                "mqld\n" +
                "lvmdqb\n" +
                "\n" +
                "iq\n" +
                "qi\n" +
                "\n" +
                "filjwt\n" +
                "fwitlj\n" +
                "fliwtj\n" +
                "wtljif\n" +
                "tjwfil\n" +
                "\n" +
                "dx\n" +
                "xd\n" +
                "dx\n" +
                "xnd\n" +
                "xd\n" +
                "\n" +
                "vzo\n" +
                "zov\n" +
                "\n" +
                "ogbwntefukpch\n" +
                "ebwnsfkgupocht\n" +
                "noctepwgfhkub\n" +
                "wfqkugnpodjthbce\n" +
                "\n" +
                "genbzqkvspy\n" +
                "brkwjevpqsczn\n" +
                "fdxnvtzsobqiekau\n" +
                "\n" +
                "nxwb\n" +
                "wnj\n" +
                "\n" +
                "imfvncxbhlrdzgok\n" +
                "vbfdakgnhlcrixmo\n" +
                "cnzbholrkvdifmxg\n" +
                "ucoklqmbdxnvigrhf\n" +
                "blndpvmhkirgcxfo\n" +
                "\n" +
                "hquykcmexvza\n" +
                "evnayxkchmzq\n" +
                "jfyxamhqpiwzeokgcvs\n" +
                "ekzdruqamhlbtvxyc\n" +
                "\n" +
                "nk\n" +
                "knwct\n" +
                "pbykwan\n" +
                "dzsegnfqrom\n" +
                "linuwk\n" +
                "\n" +
                "tbc\n" +
                "tqbe\n" +
                "tcub\n" +
                "\n" +
                "lzxybkftrhis\n" +
                "ylrxhdasutjzncipgbfw\n" +
                "xktyhfizlrobqsmv\n" +
                "\n" +
                "sjb\n" +
                "pdkaowvu\n" +
                "\n" +
                "bnhcaqjprkx\n" +
                "ncdrqxbolaijkt\n" +
                "zaxrnksqchybj\n" +
                "cbnaxejqrk\n" +
                "\n" +
                "bteqziwsumofxpvchr\n" +
                "choiepzjxuwtvfrsm\n" +
                "irtuwcsemlpvfzhox\n" +
                "twhximepcsfzorlvgu\n" +
                "\n" +
                "ta\n" +
                "at\n" +
                "\n" +
                "xjdybasehgpm\n" +
                "edaosjpgxhmby\n" +
                "xybgpdjemsha\n" +
                "dmexjpbaslhywg\n" +
                "xpmedyahjbsg\n" +
                "\n" +
                "cbjxvynghstrfluoempdk\n" +
                "idhbtapleufcsrgywnvmox\n" +
                "xohdljfecvupmsgrbytkn\n" +
                "rvleksucfbdymxgotqpnh\n" +
                "\n" +
                "klfewtsaihpxnmogudy\n" +
                "seqdufxypnlikwtogah\n" +
                "ewpohdiknstxugayfl\n" +
                "xwenydkuhfasotlgpij\n" +
                "fignpyousdtkwexalh\n" +
                "\n" +
                "oudzygfimh\n" +
                "xvj\n" +
                "\n" +
                "qbpviwoadmfr\n" +
                "dimbswlpqnh\n" +
                "yzgxbqidwuj\n" +
                "\n" +
                "ismkdvnyzajbuowlpqfr\n" +
                "vjqwufylscopgmkrdabi\n" +
                "rhbwefvqiykupsajolmd\n" +
                "msdqtukoipvfxlyjrabw\n" +
                "\n" +
                "lho\n" +
                "hol\n" +
                "jfolhv";

        List<String> groupsAnswers = Arrays.asList(data.split("\\n\\n"));

        int result = 0;

        for (String group: groupsAnswers) {
            result += countAnswersInGroup(group);
        }

        System.out.println(result);
    }

    public static int countAnswersInGroup(String groupAnsw) {
        int asnwerCounter = 0;

        String cleanGroupAnsw = groupAnsw.replaceAll("\n", "");
        char[] answers = cleanGroupAnsw.toCharArray();

        Set<Character> uniques = new HashSet<>();


        for (char anw: answers) {
            uniques.add(anw);
        }

        return uniques.size();
    }
}
